//*
// BeerProto
//
// Another beer format, written in protocol buffer.
//
// Copyright (c) 2020-2026 Ross Merrigan

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: beerproto/v1/batch.proto

package beerprotov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The shape of wine being made, for the sake of the acidity it is aimed at.
//
// Titratable acidity is the one target where wines genuinely disagree with
// each other: reds sit around 5-7 g/L as tartaric and whites 6-9, which is far
// enough apart that a single band spanning both can only say a juice is out of
// range for every wine, never that it is wrong for this one.
//
// Deliberately *not* a subdivision of StyleCategories, where a red/white split
// would sit at the wrong level (that enum names beverage classes), would leave
// existing WINE styles ambiguous, and would still say nothing about a recipe
// with no style attached — which is most of them. It is recorded per batch
// instead, beside WaterAdjustmentStrategyType, because it is the same kind of
// thing: a choice about what this batch is aiming at rather than a fact about
// what it is.
//
// UNSPECIFIED is a usable state, not a missing one: a winemaker who has not
// said gets judged against a band spanning every arm below, which is what the
// app did before this field existed.
type WineStyleType int32

const (
	WineStyleType_WINE_STYLE_TYPE_UNSPECIFIED WineStyleType = 0
	WineStyleType_WINE_STYLE_TYPE_RED         WineStyleType = 1
	WineStyleType_WINE_STYLE_TYPE_WHITE       WineStyleType = 2
	// Short skin contact, and an acidity aimed nearer a white than a red.
	WineStyleType_WINE_STYLE_TYPE_ROSE WineStyleType = 3
)

// Enum value maps for WineStyleType.
var (
	WineStyleType_name = map[int32]string{
		0: "WINE_STYLE_TYPE_UNSPECIFIED",
		1: "WINE_STYLE_TYPE_RED",
		2: "WINE_STYLE_TYPE_WHITE",
		3: "WINE_STYLE_TYPE_ROSE",
	}
	WineStyleType_value = map[string]int32{
		"WINE_STYLE_TYPE_UNSPECIFIED": 0,
		"WINE_STYLE_TYPE_RED":         1,
		"WINE_STYLE_TYPE_WHITE":       2,
		"WINE_STYLE_TYPE_ROSE":        3,
	}
)

func (x WineStyleType) Enum() *WineStyleType {
	p := new(WineStyleType)
	*p = x
	return p
}

func (x WineStyleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WineStyleType) Descriptor() protoreflect.EnumDescriptor {
	return file_beerproto_v1_batch_proto_enumTypes[0].Descriptor()
}

func (WineStyleType) Type() protoreflect.EnumType {
	return &file_beerproto_v1_batch_proto_enumTypes[0]
}

func (x WineStyleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WineStyleType.Descriptor instead.
func (WineStyleType) EnumDescriptor() ([]byte, []int) {
	return file_beerproto_v1_batch_proto_rawDescGZIP(), []int{0}
}

type BatchStatusType int32

const (
	BatchStatusType_BATCH_STATUS_TYPE_UNSPECIFIED  BatchStatusType = 0
	BatchStatusType_BATCH_STATUS_TYPE_PLANNING     BatchStatusType = 1
	BatchStatusType_BATCH_STATUS_TYPE_BREWING      BatchStatusType = 2
	BatchStatusType_BATCH_STATUS_TYPE_FERMENTING   BatchStatusType = 3
	BatchStatusType_BATCH_STATUS_TYPE_CONDITIONING BatchStatusType = 4
	BatchStatusType_BATCH_STATUS_TYPE_COMPLETED    BatchStatusType = 5
	BatchStatusType_BATCH_STATUS_TYPE_ARCHIVED     BatchStatusType = 6
)

// Enum value maps for BatchStatusType.
var (
	BatchStatusType_name = map[int32]string{
		0: "BATCH_STATUS_TYPE_UNSPECIFIED",
		1: "BATCH_STATUS_TYPE_PLANNING",
		2: "BATCH_STATUS_TYPE_BREWING",
		3: "BATCH_STATUS_TYPE_FERMENTING",
		4: "BATCH_STATUS_TYPE_CONDITIONING",
		5: "BATCH_STATUS_TYPE_COMPLETED",
		6: "BATCH_STATUS_TYPE_ARCHIVED",
	}
	BatchStatusType_value = map[string]int32{
		"BATCH_STATUS_TYPE_UNSPECIFIED":  0,
		"BATCH_STATUS_TYPE_PLANNING":     1,
		"BATCH_STATUS_TYPE_BREWING":      2,
		"BATCH_STATUS_TYPE_FERMENTING":   3,
		"BATCH_STATUS_TYPE_CONDITIONING": 4,
		"BATCH_STATUS_TYPE_COMPLETED":    5,
		"BATCH_STATUS_TYPE_ARCHIVED":     6,
	}
)

func (x BatchStatusType) Enum() *BatchStatusType {
	p := new(BatchStatusType)
	*p = x
	return p
}

func (x BatchStatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BatchStatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_beerproto_v1_batch_proto_enumTypes[1].Descriptor()
}

func (BatchStatusType) Type() protoreflect.EnumType {
	return &file_beerproto_v1_batch_proto_enumTypes[1]
}

func (x BatchStatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BatchStatusType.Descriptor instead.
func (BatchStatusType) EnumDescriptor() ([]byte, []int) {
	return file_beerproto_v1_batch_proto_rawDescGZIP(), []int{1}
}

type WaterAdjustmentStrategyType int32

const (
	WaterAdjustmentStrategyType_WATER_ADJUSTMENT_STRATEGY_TYPE_UNSPECIFIED WaterAdjustmentStrategyType = 0
	WaterAdjustmentStrategyType_WATER_ADJUSTMENT_STRATEGY_TYPE_SALTS       WaterAdjustmentStrategyType = 1
	WaterAdjustmentStrategyType_WATER_ADJUSTMENT_STRATEGY_TYPE_DILUTION    WaterAdjustmentStrategyType = 2
	WaterAdjustmentStrategyType_WATER_ADJUSTMENT_STRATEGY_TYPE_ACID        WaterAdjustmentStrategyType = 3
)

// Enum value maps for WaterAdjustmentStrategyType.
var (
	WaterAdjustmentStrategyType_name = map[int32]string{
		0: "WATER_ADJUSTMENT_STRATEGY_TYPE_UNSPECIFIED",
		1: "WATER_ADJUSTMENT_STRATEGY_TYPE_SALTS",
		2: "WATER_ADJUSTMENT_STRATEGY_TYPE_DILUTION",
		3: "WATER_ADJUSTMENT_STRATEGY_TYPE_ACID",
	}
	WaterAdjustmentStrategyType_value = map[string]int32{
		"WATER_ADJUSTMENT_STRATEGY_TYPE_UNSPECIFIED": 0,
		"WATER_ADJUSTMENT_STRATEGY_TYPE_SALTS":       1,
		"WATER_ADJUSTMENT_STRATEGY_TYPE_DILUTION":    2,
		"WATER_ADJUSTMENT_STRATEGY_TYPE_ACID":        3,
	}
)

func (x WaterAdjustmentStrategyType) Enum() *WaterAdjustmentStrategyType {
	p := new(WaterAdjustmentStrategyType)
	*p = x
	return p
}

func (x WaterAdjustmentStrategyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WaterAdjustmentStrategyType) Descriptor() protoreflect.EnumDescriptor {
	return file_beerproto_v1_batch_proto_enumTypes[2].Descriptor()
}

func (WaterAdjustmentStrategyType) Type() protoreflect.EnumType {
	return &file_beerproto_v1_batch_proto_enumTypes[2]
}

func (x WaterAdjustmentStrategyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WaterAdjustmentStrategyType.Descriptor instead.
func (WaterAdjustmentStrategyType) EnumDescriptor() ([]byte, []int) {
	return file_beerproto_v1_batch_proto_rawDescGZIP(), []int{2}
}

type MashAcidBasis int32

const (
	MashAcidBasis_MASH_ACID_BASIS_UNSPECIFIED MashAcidBasis = 0
	// Sized from the recipe's predicted mash pH, before the mash is in.
	MashAcidBasis_MASH_ACID_BASIS_ESTIMATE MashAcidBasis = 1
	// Sized from a meter reading taken on the mash itself.
	MashAcidBasis_MASH_ACID_BASIS_MEASUREMENT MashAcidBasis = 2
)

// Enum value maps for MashAcidBasis.
var (
	MashAcidBasis_name = map[int32]string{
		0: "MASH_ACID_BASIS_UNSPECIFIED",
		1: "MASH_ACID_BASIS_ESTIMATE",
		2: "MASH_ACID_BASIS_MEASUREMENT",
	}
	MashAcidBasis_value = map[string]int32{
		"MASH_ACID_BASIS_UNSPECIFIED": 0,
		"MASH_ACID_BASIS_ESTIMATE":    1,
		"MASH_ACID_BASIS_MEASUREMENT": 2,
	}
)

func (x MashAcidBasis) Enum() *MashAcidBasis {
	p := new(MashAcidBasis)
	*p = x
	return p
}

func (x MashAcidBasis) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MashAcidBasis) Descriptor() protoreflect.EnumDescriptor {
	return file_beerproto_v1_batch_proto_enumTypes[3].Descriptor()
}

func (MashAcidBasis) Type() protoreflect.EnumType {
	return &file_beerproto_v1_batch_proto_enumTypes[3]
}

func (x MashAcidBasis) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MashAcidBasis.Descriptor instead.
func (MashAcidBasis) EnumDescriptor() ([]byte, []int) {
	return file_beerproto_v1_batch_proto_rawDescGZIP(), []int{3}
}

type GrowthModel int32

const (
	GrowthModel_GROWTH_MODEL_UNSPECIFIED GrowthModel = 0
	// Braukaiser - Stir Plate
	GrowthModel_GROWTH_MODEL_BRAUKAISER GrowthModel = 1
	// C. White - No Agitation
	GrowthModel_GROWTH_MODEL_C_WHITE_NO_AGITATION GrowthModel = 2
	// C. White - Shaking
	GrowthModel_GROWTH_MODEL_C_WHITE_SHAKING GrowthModel = 3
)

// Enum value maps for GrowthModel.
var (
	GrowthModel_name = map[int32]string{
		0: "GROWTH_MODEL_UNSPECIFIED",
		1: "GROWTH_MODEL_BRAUKAISER",
		2: "GROWTH_MODEL_C_WHITE_NO_AGITATION",
		3: "GROWTH_MODEL_C_WHITE_SHAKING",
	}
	GrowthModel_value = map[string]int32{
		"GROWTH_MODEL_UNSPECIFIED":          0,
		"GROWTH_MODEL_BRAUKAISER":           1,
		"GROWTH_MODEL_C_WHITE_NO_AGITATION": 2,
		"GROWTH_MODEL_C_WHITE_SHAKING":      3,
	}
)

func (x GrowthModel) Enum() *GrowthModel {
	p := new(GrowthModel)
	*p = x
	return p
}

func (x GrowthModel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GrowthModel) Descriptor() protoreflect.EnumDescriptor {
	return file_beerproto_v1_batch_proto_enumTypes[4].Descriptor()
}

func (GrowthModel) Type() protoreflect.EnumType {
	return &file_beerproto_v1_batch_proto_enumTypes[4]
}

func (x GrowthModel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GrowthModel.Descriptor instead.
func (GrowthModel) EnumDescriptor() ([]byte, []int) {
	return file_beerproto_v1_batch_proto_rawDescGZIP(), []int{4}
}

type Batch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The recipe this batch was brewed from.
	//
	// Batch holds no RecipeType of its own, so this is the whole of its link to
	// one, and what keeps a Batch meaningful on its own. How the recipe is then
	// resolved — a live document, a snapshot frozen at brew time, a file
	// alongside — is left to whatever stores the batch.
	RecipeId                string                      `protobuf:"bytes,2,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	Name                    string                      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Batch                   uint32                      `protobuf:"varint,4,opt,name=batch,proto3" json:"batch,omitempty"`
	Date                    *timestamppb.Timestamp      `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Status                  BatchStatusType             `protobuf:"varint,6,opt,name=status,proto3,enum=beerproto.v1.BatchStatusType" json:"status,omitempty"`
	BrewStep                uint32                      `protobuf:"varint,7,opt,name=brew_step,json=brewStep,proto3" json:"brew_step,omitempty"`
	Equipment               *EquipmentType              `protobuf:"bytes,8,opt,name=equipment,proto3" json:"equipment,omitempty"`
	Starters                []*Starter                  `protobuf:"bytes,9,rep,name=starters,proto3" json:"starters,omitempty"`
	WaterAdjustmentStrategy WaterAdjustmentStrategyType `protobuf:"varint,10,opt,name=water_adjustment_strategy,json=waterAdjustmentStrategy,proto3,enum=beerproto.v1.WaterAdjustmentStrategyType" json:"water_adjustment_strategy,omitempty"`
	MashAcidAdditions       []*MashAcidAddition         `protobuf:"bytes,11,rep,name=mash_acid_additions,json=mashAcidAdditions,proto3" json:"mash_acid_additions,omitempty"`
	FermentationProfile     *FermentationProfile        `protobuf:"bytes,12,opt,name=fermentation_profile,json=fermentationProfile,proto3" json:"fermentation_profile,omitempty"`
	Measurements            *Measurements               `protobuf:"bytes,13,opt,name=measurements,proto3" json:"measurements,omitempty"`
	// What the recipe predicted, frozen at Brew. See Estimates.
	Estimates *Estimates `protobuf:"bytes,14,opt,name=estimates,proto3" json:"estimates,omitempty"`
	Logs      []*Log     `protobuf:"bytes,15,rep,name=logs,proto3" json:"logs,omitempty"`
	Notes     string     `protobuf:"bytes,16,opt,name=notes,proto3" json:"notes,omitempty"`
	Rating    float64    `protobuf:"fixed64,17,opt,name=rating,proto3" json:"rating,omitempty"`
	// Which acidity target a wine is being made to. Empty for anything that is
	// not wine.
	WineStyle     WineStyleType `protobuf:"varint,18,opt,name=wine_style,json=wineStyle,proto3,enum=beerproto.v1.WineStyleType" json:"wine_style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_beerproto_v1_batch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_beerproto_v1_batch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_beerproto_v1_batch_proto_rawDescGZIP(), []int{0}
}

func (x *Batch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Batch) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *Batch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Batch) GetBatch() uint32 {
	if x != nil {
		return x.Batch
	}
	return 0
}

func (x *Batch) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Batch) GetStatus() BatchStatusType {
	if x != nil {
		return x.Status
	}
	return BatchStatusType_BATCH_STATUS_TYPE_UNSPECIFIED
}

func (x *Batch) GetBrewStep() uint32 {
	if x != nil {
		return x.BrewStep
	}
	return 0
}

func (x *Batch) GetEquipment() *EquipmentType {
	if x != nil {
		return x.Equipment
	}
	return nil
}

func (x *Batch) GetStarters() []*Starter {
	if x != nil {
		return x.Starters
	}
	return nil
}

func (x *Batch) GetWaterAdjustmentStrategy() WaterAdjustmentStrategyType {
	if x != nil {
		return x.WaterAdjustmentStrategy
	}
	return WaterAdjustmentStrategyType_WATER_ADJUSTMENT_STRATEGY_TYPE_UNSPECIFIED
}

func (x *Batch) GetMashAcidAdditions() []*MashAcidAddition {
	if x != nil {
		return x.MashAcidAdditions
	}
	return nil
}

func (x *Batch) GetFermentationProfile() *FermentationProfile {
	if x != nil {
		return x.FermentationProfile
	}
	return nil
}

func (x *Batch) GetMeasurements() *Measurements {
	if x != nil {
		return x.Measurements
	}
	return nil
}

func (x *Batch) GetEstimates() *Estimates {
	if x != nil {
		return x.Estimates
	}
	return nil
}

func (x *Batch) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *Batch) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Batch) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Batch) GetWineStyle() WineStyleType {
	if x != nil {
		return x.WineStyle
	}
	return WineStyleType_WINE_STYLE_TYPE_UNSPECIFIED
}

// An acid dose the brewer has committed to for this batch's mash.
//
// The planning panel derives a recommendation live from the recipe's grist and
// the brewhouse's water; this is what the brewer confirmed from it, frozen at
// that moment. A later edit to the grain bill or the water profile moves the
// recommendation but must not rewrite what actually went into the tun.
//
// Recorded on the batch rather than the recipe because the dose depends on the
// brewhouse — its source water, and which acid is on its shelf.
type MashAcidAddition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Acid  AcidType               `protobuf:"varint,2,opt,name=acid,proto3,enum=beerproto.v1.AcidType" json:"acid,omitempty"`
	// Millilitres of solution, or grams of malt for an acid dosed by mass
	// (acidulated malt). The acid says which — there is no separate unit here.
	Amount float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// The pH this dose was sized to reach.
	TargetPh *AcidityType `protobuf:"bytes,4,opt,name=target_ph,json=targetPh,proto3" json:"target_ph,omitempty"`
	// The pH it was sized from: the app's prediction, or a meter reading.
	FromPh *AcidityType `protobuf:"bytes,5,opt,name=from_ph,json=fromPh,proto3" json:"from_ph,omitempty"`
	// Which of those two `from_ph` was — the difference matters, because a dose
	// computed from a reading is worth more than one computed from a model.
	Basis MashAcidBasis `protobuf:"varint,6,opt,name=basis,proto3,enum=beerproto.v1.MashAcidBasis" json:"basis,omitempty"`
	// The liquor volume the dose was sized against.
	Volume        *VolumeType            `protobuf:"bytes,7,opt,name=volume,proto3" json:"volume,omitempty"`
	Confirmed     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MashAcidAddition) Reset() {
	*x = MashAcidAddition{}
	mi := &file_beerproto_v1_batch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MashAcidAddition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MashAcidAddition) ProtoMessage() {}

func (x *MashAcidAddition) ProtoReflect() protoreflect.Message {
	mi := &file_beerproto_v1_batch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MashAcidAddition.ProtoReflect.Descriptor instead.
func (*MashAcidAddition) Descriptor() ([]byte, []int) {
	return file_beerproto_v1_batch_proto_rawDescGZIP(), []int{1}
}

func (x *MashAcidAddition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MashAcidAddition) GetAcid() AcidType {
	if x != nil {
		return x.Acid
	}
	return AcidType_ACID_TYPE_UNSPECIFIED
}

func (x *MashAcidAddition) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MashAcidAddition) GetTargetPh() *AcidityType {
	if x != nil {
		return x.TargetPh
	}
	return nil
}

func (x *MashAcidAddition) GetFromPh() *AcidityType {
	if x != nil {
		return x.FromPh
	}
	return nil
}

func (x *MashAcidAddition) GetBasis() MashAcidBasis {
	if x != nil {
		return x.Basis
	}
	return MashAcidBasis_MASH_ACID_BASIS_UNSPECIFIED
}

func (x *MashAcidAddition) GetVolume() *VolumeType {
	if x != nil {
		return x.Volume
	}
	return nil
}

func (x *MashAcidAddition) GetConfirmed() *timestamppb.Timestamp {
	if x != nil {
		return x.Confirmed
	}
	return nil
}

// A yeast starter for one culture addition on a batch. Holds both the step-up
// plan (steps) and the brew-day execution inputs (pitch_rate, yeast_date) plus
// a frozen snapshot of the computed pitch result (pitch).
type Starter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Steps []*StarterStep         `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	// Binds this starter to a CultureAddition (CultureAdditionType.id).
	CultureId string `protobuf:"bytes,3,opt,name=culture_id,json=cultureId,proto3" json:"culture_id,omitempty"`
	// Target pitch rate in M cells / mL / °Plato.
	PitchRate *PitchRateType `protobuf:"bytes,4,opt,name=pitch_rate,json=pitchRate,proto3" json:"pitch_rate,omitempty"`
	// Yeast manufacture / production date — drives liquid-yeast viability decay.
	YeastDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=yeast_date,json=yeastDate,proto3" json:"yeast_date,omitempty"`
	// As-brewed snapshot of the computed pitch-rate result.
	Pitch         *CulturePitchRate `protobuf:"bytes,6,opt,name=pitch,proto3" json:"pitch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Starter) Reset() {
	*x = Starter{}
	mi := &file_beerproto_v1_batch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Starter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Starter) ProtoMessage() {}

func (x *Starter) ProtoReflect() protoreflect.Message {
	mi := &file_beerproto_v1_batch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Starter.ProtoReflect.Descriptor instead.
func (*Starter) Descriptor() ([]byte, []int) {
	return file_beerproto_v1_batch_proto_rawDescGZIP(), []int{2}
}

func (x *Starter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Starter) GetSteps() []*StarterStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Starter) GetCultureId() string {
	if x != nil {
		return x.CultureId
	}
	return ""
}

func (x *Starter) GetPitchRate() *PitchRateType {
	if x != nil {
		return x.PitchRate
	}
	return nil
}

func (x *Starter) GetYeastDate() *timestamppb.Timestamp {
	if x != nil {
		return x.YeastDate
	}
	return nil
}

func (x *Starter) GetPitch() *CulturePitchRate {
	if x != nil {
		return x.Pitch
	}
	return nil
}

type StarterStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StarterSize   *VolumeType            `protobuf:"bytes,2,opt,name=starter_size,json=starterSize,proto3" json:"starter_size,omitempty"`
	Gravity       *GravityType           `protobuf:"bytes,3,opt,name=gravity,proto3" json:"gravity,omitempty"`
	Model         GrowthModel            `protobuf:"varint,4,opt,name=model,proto3,enum=beerproto.v1.GrowthModel" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarterStep) Reset() {
	*x = StarterStep{}
	mi := &file_beerproto_v1_batch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarterStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarterStep) ProtoMessage() {}

func (x *StarterStep) ProtoReflect() protoreflect.Message {
	mi := &file_beerproto_v1_batch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarterStep.ProtoReflect.Descriptor instead.
func (*StarterStep) Descriptor() ([]byte, []int) {
	return file_beerproto_v1_batch_proto_rawDescGZIP(), []int{3}
}

func (x *StarterStep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StarterStep) GetStarterSize() *VolumeType {
	if x != nil {
		return x.StarterSize
	}
	return nil
}

func (x *StarterStep) GetGravity() *GravityType {
	if x != nil {
		return x.Gravity
	}
	return nil
}

func (x *StarterStep) GetModel() GrowthModel {
	if x != nil {
		return x.Model
	}
	return GrowthModel_GROWTH_MODEL_UNSPECIFIED
}

// Derived per-step growth result — computed from a StarterStep, not persisted.
type StepRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dme           *MassType              `protobuf:"bytes,1,opt,name=dme,proto3" json:"dme,omitempty"`
	GrowthRate    float64                `protobuf:"fixed64,2,opt,name=growth_rate,json=growthRate,proto3" json:"growth_rate,omitempty"`
	EndingCount   *CellCountType         `protobuf:"bytes,3,opt,name=ending_count,json=endingCount,proto3" json:"ending_count,omitempty"`
	PitchRate     *PitchRateType         `protobuf:"bytes,4,opt,name=pitch_rate,json=pitchRate,proto3" json:"pitch_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepRate) Reset() {
	*x = StepRate{}
	mi := &file_beerproto_v1_batch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepRate) ProtoMessage() {}

func (x *StepRate) ProtoReflect() protoreflect.Message {
	mi := &file_beerproto_v1_batch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepRate.ProtoReflect.Descriptor instead.
func (*StepRate) Descriptor() ([]byte, []int) {
	return file_beerproto_v1_batch_proto_rawDescGZIP(), []int{4}
}

func (x *StepRate) GetDme() *MassType {
	if x != nil {
		return x.Dme
	}
	return nil
}

func (x *StepRate) GetGrowthRate() float64 {
	if x != nil {
		return x.GrowthRate
	}
	return 0
}

func (x *StepRate) GetEndingCount() *CellCountType {
	if x != nil {
		return x.EndingCount
	}
	return nil
}

func (x *StepRate) GetPitchRate() *PitchRateType {
	if x != nil {
		return x.PitchRate
	}
	return nil
}

type CulturePitchRate struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TargetPitchRateCells *CellCountType         `protobuf:"bytes,1,opt,name=target_pitch_rate_cells,json=targetPitchRateCells,proto3" json:"target_pitch_rate_cells,omitempty"`
	CellsAvailable       *CellCountType         `protobuf:"bytes,2,opt,name=cells_available,json=cellsAvailable,proto3" json:"cells_available,omitempty"`
	Difference           *CellCountType         `protobuf:"bytes,3,opt,name=difference,proto3" json:"difference,omitempty"`
	PitchRateAsIs        *PitchRateType         `protobuf:"bytes,4,opt,name=pitch_rate_as_is,json=pitchRateAsIs,proto3" json:"pitch_rate_as_is,omitempty"`
	Viability            *PercentType           `protobuf:"bytes,5,opt,name=viability,proto3" json:"viability,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CulturePitchRate) Reset() {
	*x = CulturePitchRate{}
	mi := &file_beerproto_v1_batch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CulturePitchRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CulturePitchRate) ProtoMessage() {}

func (x *CulturePitchRate) ProtoReflect() protoreflect.Message {
	mi := &file_beerproto_v1_batch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CulturePitchRate.ProtoReflect.Descriptor instead.
func (*CulturePitchRate) Descriptor() ([]byte, []int) {
	return file_beerproto_v1_batch_proto_rawDescGZIP(), []int{5}
}

func (x *CulturePitchRate) GetTargetPitchRateCells() *CellCountType {
	if x != nil {
		return x.TargetPitchRateCells
	}
	return nil
}

func (x *CulturePitchRate) GetCellsAvailable() *CellCountType {
	if x != nil {
		return x.CellsAvailable
	}
	return nil
}

func (x *CulturePitchRate) GetDifference() *CellCountType {
	if x != nil {
		return x.Difference
	}
	return nil
}

func (x *CulturePitchRate) GetPitchRateAsIs() *PitchRateType {
	if x != nil {
		return x.PitchRateAsIs
	}
	return nil
}

func (x *CulturePitchRate) GetViability() *PercentType {
	if x != nil {
		return x.Viability
	}
	return nil
}

// One dated, stage-tagged entry a person wrote against the batch.
//
// A log is the brewer's own record. Machine-generated time series belong in
// BatchReading, which is stored separately precisely so it can be numerous.
type Log struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Notes  string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	Status BatchStatusType        `protobuf:"varint,4,opt,name=status,proto3,enum=beerproto.v1.BatchStatusType" json:"status,omitempty"`
	// Superseded by BatchReading.gravity / .temperature, which can also carry pH
	// and pressure and can say where the number came from. Kept because existing
	// batches hold their fermentation series here and the charts read it; not
	// marked deprecated yet, so regenerating this schema does not light up every
	// call site before there is somewhere else for them to go.
	Gravity     *GravityType     `protobuf:"bytes,5,opt,name=gravity,proto3" json:"gravity,omitempty"`
	Temperature *TemperatureType `protobuf:"bytes,6,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// Set on the entries where the brewer actually sat down with a glass.
	Taste         *Taste `protobuf:"bytes,7,opt,name=taste,proto3" json:"taste,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_beerproto_v1_batch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_beerproto_v1_batch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_beerproto_v1_batch_proto_rawDescGZIP(), []int{6}
}

func (x *Log) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Log) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Log) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Log) GetStatus() BatchStatusType {
	if x != nil {
		return x.Status
	}
	return BatchStatusType_BATCH_STATUS_TYPE_UNSPECIFIED
}

func (x *Log) GetGravity() *GravityType {
	if x != nil {
		return x.Gravity
	}
	return nil
}

func (x *Log) GetTemperature() *TemperatureType {
	if x != nil {
		return x.Temperature
	}
	return nil
}

func (x *Log) GetTaste() *Taste {
	if x != nil {
		return x.Taste
	}
	return nil
}

// A tasting recorded against a log entry.
//
// Hangs off Log rather than forming a list of its own because a tasting is a
// dated, stage-tagged observation — exactly what Log already is. A parallel
// list would restate the timestamp, the status and the notes, and then drift
// out of agreement with them.
//
// This is what `Batch.rating` (12) and `beerproto.TasteType` cannot do: a
// single scalar says how the beer turned out, and says nothing about whether
// six weeks in the cellar helped, which is the question a conditioning or
// lagering batch exists to answer.
type Taste struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall mark, on the same scale as beerproto.TasteType.rating so the two
	// can be compared and the last tasting can settle the batch's own rating.
	Rating float64 `protobuf:"fixed64,1,opt,name=rating,proto3" json:"rating,omitempty"`
	Notes  string  `protobuf:"bytes,2,opt,name=notes,proto3" json:"notes,omitempty"`
	// Perceived intensities on the same scale as `rating`. All optional — a quick
	// tasting sets rating and notes and leaves these alone. Deliberately a short
	// list of axes a brewer can rank consistently against their own previous
	// tastings, which is what makes a series of them worth plotting; this is not
	// a style score and not a competition sheet.
	Bitterness    float64 `protobuf:"fixed64,3,opt,name=bitterness,proto3" json:"bitterness,omitempty"`
	Sweetness     float64 `protobuf:"fixed64,4,opt,name=sweetness,proto3" json:"sweetness,omitempty"`
	Body          float64 `protobuf:"fixed64,5,opt,name=body,proto3" json:"body,omitempty"`
	Aroma         float64 `protobuf:"fixed64,6,opt,name=aroma,proto3" json:"aroma,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Taste) Reset() {
	*x = Taste{}
	mi := &file_beerproto_v1_batch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Taste) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Taste) ProtoMessage() {}

func (x *Taste) ProtoReflect() protoreflect.Message {
	mi := &file_beerproto_v1_batch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Taste.ProtoReflect.Descriptor instead.
func (*Taste) Descriptor() ([]byte, []int) {
	return file_beerproto_v1_batch_proto_rawDescGZIP(), []int{7}
}

func (x *Taste) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Taste) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Taste) GetBitterness() float64 {
	if x != nil {
		return x.Bitterness
	}
	return 0
}

func (x *Taste) GetSweetness() float64 {
	if x != nil {
		return x.Sweetness
	}
	return 0
}

func (x *Taste) GetBody() float64 {
	if x != nil {
		return x.Body
	}
	return 0
}

func (x *Taste) GetAroma() float64 {
	if x != nil {
		return x.Aroma
	}
	return 0
}

type FermentationProfile struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FermentationStart *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=fermentation_start,json=fermentationStart,proto3" json:"fermentation_start,omitempty"`
	BottlingDate      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=bottling_date,json=bottlingDate,proto3" json:"bottling_date,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FermentationProfile) Reset() {
	*x = FermentationProfile{}
	mi := &file_beerproto_v1_batch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FermentationProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FermentationProfile) ProtoMessage() {}

func (x *FermentationProfile) ProtoReflect() protoreflect.Message {
	mi := &file_beerproto_v1_batch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FermentationProfile.ProtoReflect.Descriptor instead.
func (*FermentationProfile) Descriptor() ([]byte, []int) {
	return file_beerproto_v1_batch_proto_rawDescGZIP(), []int{8}
}

func (x *FermentationProfile) GetFermentationStart() *timestamppb.Timestamp {
	if x != nil {
		return x.FermentationStart
	}
	return nil
}

func (x *FermentationProfile) GetBottlingDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BottlingDate
	}
	return nil
}

// What was actually observed on this batch, as against what the recipe
// predicted (Estimates, and the recipe's own stored figures).
//
// Observations only. A change to the plan — a substituted hop, a different
// weight — is a design change, and belongs with the recipe rather than here.
type Measurements struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Volumes, roughly in process order.
	//
	// NOTE: two pairs here overlap and the difference is not written down
	// anywhere. `boil_volume` and `pre_boil_volume` are separate labelled fields
	// in the pre-boil group; `bottling_volume` is collected at conditioning and
	// `packaging_volume` at completion. Both pairs are live, so neither can just
	// be dropped, but which one a brewer should fill in is undocumented.
	BoilVolume           *VolumeType `protobuf:"bytes,1,opt,name=boil_volume,json=boilVolume,proto3" json:"boil_volume,omitempty"`
	PreBoilVolume        *VolumeType `protobuf:"bytes,2,opt,name=pre_boil_volume,json=preBoilVolume,proto3" json:"pre_boil_volume,omitempty"`
	PostBoilKettleVolume *VolumeType `protobuf:"bytes,3,opt,name=post_boil_kettle_volume,json=postBoilKettleVolume,proto3" json:"post_boil_kettle_volume,omitempty"`
	BatchVolume          *VolumeType `protobuf:"bytes,4,opt,name=batch_volume,json=batchVolume,proto3" json:"batch_volume,omitempty"`
	FermenterVolume      *VolumeType `protobuf:"bytes,5,opt,name=fermenter_volume,json=fermenterVolume,proto3" json:"fermenter_volume,omitempty"`
	FermenterTopup       *VolumeType `protobuf:"bytes,6,opt,name=fermenter_topup,json=fermenterTopup,proto3" json:"fermenter_topup,omitempty"`
	BottlingVolume       *VolumeType `protobuf:"bytes,7,opt,name=bottling_volume,json=bottlingVolume,proto3" json:"bottling_volume,omitempty"`
	PackagingVolume      *VolumeType `protobuf:"bytes,8,opt,name=packaging_volume,json=packagingVolume,proto3" json:"packaging_volume,omitempty"`
	BoilOffPerHour       *VolumeType `protobuf:"bytes,9,opt,name=boil_off_per_hour,json=boilOffPerHour,proto3" json:"boil_off_per_hour,omitempty"`
	// Gravities, in process order.
	//
	// `first_wort_gravity` is the first runnings, before any sparge is collected.
	// Read together with pre_boil_gravity it separates conversion in the tun from
	// how well the grain bed was rinsed — the measurement
	// `conversion_efficiency` needs.
	FirstWortGravity *GravityType `protobuf:"bytes,10,opt,name=first_wort_gravity,json=firstWortGravity,proto3" json:"first_wort_gravity,omitempty"`
	PreBoilGravity   *GravityType `protobuf:"bytes,11,opt,name=pre_boil_gravity,json=preBoilGravity,proto3" json:"pre_boil_gravity,omitempty"`
	PostBoilGravity  *GravityType `protobuf:"bytes,12,opt,name=post_boil_gravity,json=postBoilGravity,proto3" json:"post_boil_gravity,omitempty"`
	OriginalGravity  *GravityType `protobuf:"bytes,13,opt,name=original_gravity,json=originalGravity,proto3" json:"original_gravity,omitempty"`
	FinalGravity     *GravityType `protobuf:"bytes,14,opt,name=final_gravity,json=finalGravity,proto3" json:"final_gravity,omitempty"`
	// All four halves of beerproto.EfficiencyType. Brewhouse plans every one of
	// them, and this used to measure only mash and brewhouse, which made the
	// other two impossible to check against the plan. Lauter is what other tools
	// call kettle efficiency.
	ConversionEfficiency *PercentType `protobuf:"bytes,15,opt,name=conversion_efficiency,json=conversionEfficiency,proto3" json:"conversion_efficiency,omitempty"`
	LauterEfficiency     *PercentType `protobuf:"bytes,16,opt,name=lauter_efficiency,json=lauterEfficiency,proto3" json:"lauter_efficiency,omitempty"`
	MashEfficiency       *PercentType `protobuf:"bytes,17,opt,name=mash_efficiency,json=mashEfficiency,proto3" json:"mash_efficiency,omitempty"`
	BrewhouseEfficiency  *PercentType `protobuf:"bytes,18,opt,name=brewhouse_efficiency,json=brewhouseEfficiency,proto3" json:"brewhouse_efficiency,omitempty"`
	AlcoholByVolume      *PercentType `protobuf:"bytes,19,opt,name=alcohol_by_volume,json=alcoholByVolume,proto3" json:"alcohol_by_volume,omitempty"`
	Attenuation          *PercentType `protobuf:"bytes,20,opt,name=attenuation,proto3" json:"attenuation,omitempty"`
	Color                *ColorType   `protobuf:"bytes,21,opt,name=color,proto3" json:"color,omitempty"`
	// Measured bitterness — a lab assay, not a formula result. The recipe's IBU
	// is a prediction and belongs to the recipe, and `adjusted_recipe` only ever
	// holds design changes, so neither is a place to write down what came back
	// from the lab. Expect it empty on most batches.
	Bitterness *BitternessType `protobuf:"bytes,22,opt,name=bitterness,proto3" json:"bitterness,omitempty"`
	MashPh     *AcidityType    `protobuf:"bytes,23,opt,name=mash_ph,json=mashPh,proto3" json:"mash_ph,omitempty"`
	// Measured counterpart to RecipeType.beer_ph, which was a target with nothing
	// to compare against.
	BeerPh *AcidityType `protobuf:"bytes,24,opt,name=beer_ph,json=beerPh,proto3" json:"beer_ph,omitempty"`
	// What the boil actually ran for, as against the brewhouse's planned
	// boil_time. Drives the real boil-off rate.
	BoilTime               *TimeType        `protobuf:"bytes,25,opt,name=boil_time,json=boilTime,proto3" json:"boil_time,omitempty"`
	CarbonationTemperature *TemperatureType `protobuf:"bytes,26,opt,name=carbonation_temperature,json=carbonationTemperature,proto3" json:"carbonation_temperature,omitempty"`
	// Titratable acidity, off a titration rather than a meter.
	//
	// The counterpart to beer_ph for anything fermenting juice. pH decides
	// whether sulfite can protect a cider; TA decides whether it is drinkable,
	// and the two are not derivable from one another. Expect it empty on beer,
	// where nothing is titrated.
	TitratableAcidity *TitratableAcidityType `protobuf:"bytes,27,opt,name=titratable_acidity,json=titratableAcidity,proto3" json:"titratable_acidity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Measurements) Reset() {
	*x = Measurements{}
	mi := &file_beerproto_v1_batch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Measurements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Measurements) ProtoMessage() {}

func (x *Measurements) ProtoReflect() protoreflect.Message {
	mi := &file_beerproto_v1_batch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Measurements.ProtoReflect.Descriptor instead.
func (*Measurements) Descriptor() ([]byte, []int) {
	return file_beerproto_v1_batch_proto_rawDescGZIP(), []int{9}
}

func (x *Measurements) GetBoilVolume() *VolumeType {
	if x != nil {
		return x.BoilVolume
	}
	return nil
}

func (x *Measurements) GetPreBoilVolume() *VolumeType {
	if x != nil {
		return x.PreBoilVolume
	}
	return nil
}

func (x *Measurements) GetPostBoilKettleVolume() *VolumeType {
	if x != nil {
		return x.PostBoilKettleVolume
	}
	return nil
}

func (x *Measurements) GetBatchVolume() *VolumeType {
	if x != nil {
		return x.BatchVolume
	}
	return nil
}

func (x *Measurements) GetFermenterVolume() *VolumeType {
	if x != nil {
		return x.FermenterVolume
	}
	return nil
}

func (x *Measurements) GetFermenterTopup() *VolumeType {
	if x != nil {
		return x.FermenterTopup
	}
	return nil
}

func (x *Measurements) GetBottlingVolume() *VolumeType {
	if x != nil {
		return x.BottlingVolume
	}
	return nil
}

func (x *Measurements) GetPackagingVolume() *VolumeType {
	if x != nil {
		return x.PackagingVolume
	}
	return nil
}

func (x *Measurements) GetBoilOffPerHour() *VolumeType {
	if x != nil {
		return x.BoilOffPerHour
	}
	return nil
}

func (x *Measurements) GetFirstWortGravity() *GravityType {
	if x != nil {
		return x.FirstWortGravity
	}
	return nil
}

func (x *Measurements) GetPreBoilGravity() *GravityType {
	if x != nil {
		return x.PreBoilGravity
	}
	return nil
}

func (x *Measurements) GetPostBoilGravity() *GravityType {
	if x != nil {
		return x.PostBoilGravity
	}
	return nil
}

func (x *Measurements) GetOriginalGravity() *GravityType {
	if x != nil {
		return x.OriginalGravity
	}
	return nil
}

func (x *Measurements) GetFinalGravity() *GravityType {
	if x != nil {
		return x.FinalGravity
	}
	return nil
}

func (x *Measurements) GetConversionEfficiency() *PercentType {
	if x != nil {
		return x.ConversionEfficiency
	}
	return nil
}

func (x *Measurements) GetLauterEfficiency() *PercentType {
	if x != nil {
		return x.LauterEfficiency
	}
	return nil
}

func (x *Measurements) GetMashEfficiency() *PercentType {
	if x != nil {
		return x.MashEfficiency
	}
	return nil
}

func (x *Measurements) GetBrewhouseEfficiency() *PercentType {
	if x != nil {
		return x.BrewhouseEfficiency
	}
	return nil
}

func (x *Measurements) GetAlcoholByVolume() *PercentType {
	if x != nil {
		return x.AlcoholByVolume
	}
	return nil
}

func (x *Measurements) GetAttenuation() *PercentType {
	if x != nil {
		return x.Attenuation
	}
	return nil
}

func (x *Measurements) GetColor() *ColorType {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *Measurements) GetBitterness() *BitternessType {
	if x != nil {
		return x.Bitterness
	}
	return nil
}

func (x *Measurements) GetMashPh() *AcidityType {
	if x != nil {
		return x.MashPh
	}
	return nil
}

func (x *Measurements) GetBeerPh() *AcidityType {
	if x != nil {
		return x.BeerPh
	}
	return nil
}

func (x *Measurements) GetBoilTime() *TimeType {
	if x != nil {
		return x.BoilTime
	}
	return nil
}

func (x *Measurements) GetCarbonationTemperature() *TemperatureType {
	if x != nil {
		return x.CarbonationTemperature
	}
	return nil
}

func (x *Measurements) GetTitratableAcidity() *TitratableAcidityType {
	if x != nil {
		return x.TitratableAcidity
	}
	return nil
}

// The few predicted figures a recipe has nowhere to put.
//
// Most of what a batch predicts is already on RecipeType, which stores
// original_gravity, final_gravity, color_estimate, alcohol_by_volume,
// apparent_attenuation, batch_size, the four efficiencies and the IBU method.
// Restating those here would only create a second place for them to disagree.
//
// These five have nowhere else to go: there is no field for the IBU value
// itself (only ibu_estimate.method), none for predicted mash pH, and none for
// the pre-boil figures, which depend on the system the beer is brewed on and
// so cannot belong to a recipe at all.
//
// Written once, when the batch is brewed, and never recomputed — which is the
// whole point. Every figure here depends on a formula choice, and re-deriving
// them later against different choices silently rewrites what the batch
// predicted on the day, destroying the one comparison a batch record exists to
// support.
type Estimates struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PreBoilVolume  *VolumeType            `protobuf:"bytes,1,opt,name=pre_boil_volume,json=preBoilVolume,proto3" json:"pre_boil_volume,omitempty"`
	PreBoilGravity *GravityType           `protobuf:"bytes,2,opt,name=pre_boil_gravity,json=preBoilGravity,proto3" json:"pre_boil_gravity,omitempty"`
	Bitterness     *BitternessType        `protobuf:"bytes,3,opt,name=bitterness,proto3" json:"bitterness,omitempty"`
	MashPh         *AcidityType           `protobuf:"bytes,4,opt,name=mash_ph,json=mashPh,proto3" json:"mash_ph,omitempty"`
	// Which model sized the mash pH prediction. Recorded with it because the two
	// models disagree, and a frozen figure whose method is unknown is only
	// half-frozen. The IBU method needs no counterpart here — RecipeType's
	// ibu_estimate already carries it.
	MashPhModel   MashPhModel `protobuf:"varint,5,opt,name=mash_ph_model,json=mashPhModel,proto3,enum=beerproto.v1.MashPhModel" json:"mash_ph_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Estimates) Reset() {
	*x = Estimates{}
	mi := &file_beerproto_v1_batch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Estimates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Estimates) ProtoMessage() {}

func (x *Estimates) ProtoReflect() protoreflect.Message {
	mi := &file_beerproto_v1_batch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Estimates.ProtoReflect.Descriptor instead.
func (*Estimates) Descriptor() ([]byte, []int) {
	return file_beerproto_v1_batch_proto_rawDescGZIP(), []int{10}
}

func (x *Estimates) GetPreBoilVolume() *VolumeType {
	if x != nil {
		return x.PreBoilVolume
	}
	return nil
}

func (x *Estimates) GetPreBoilGravity() *GravityType {
	if x != nil {
		return x.PreBoilGravity
	}
	return nil
}

func (x *Estimates) GetBitterness() *BitternessType {
	if x != nil {
		return x.Bitterness
	}
	return nil
}

func (x *Estimates) GetMashPh() *AcidityType {
	if x != nil {
		return x.MashPh
	}
	return nil
}

func (x *Estimates) GetMashPhModel() MashPhModel {
	if x != nil {
		return x.MashPhModel
	}
	return MashPhModel_MASH_PH_MODEL_UNSPECIFIED
}

var File_beerproto_v1_batch_proto protoreflect.FileDescriptor

const file_beerproto_v1_batch_proto_rawDesc = "" +
	"\n" +
	"\x18beerproto/v1/batch.proto\x12\fbeerproto.v1\x1a\x1cbeerproto/v1/equipment.proto\x1a$beerproto/v1/measureable_units.proto\x1a\x18beerproto/v1/water.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe5\x06\n" +
	"\x05Batch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trecipe_id\x18\x02 \x01(\tR\brecipeId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05batch\x18\x04 \x01(\rR\x05batch\x12.\n" +
	"\x04date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x125\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1d.beerproto.v1.BatchStatusTypeR\x06status\x12\x1b\n" +
	"\tbrew_step\x18\a \x01(\rR\bbrewStep\x129\n" +
	"\tequipment\x18\b \x01(\v2\x1b.beerproto.v1.EquipmentTypeR\tequipment\x121\n" +
	"\bstarters\x18\t \x03(\v2\x15.beerproto.v1.StarterR\bstarters\x12e\n" +
	"\x19water_adjustment_strategy\x18\n" +
	" \x01(\x0e2).beerproto.v1.WaterAdjustmentStrategyTypeR\x17waterAdjustmentStrategy\x12N\n" +
	"\x13mash_acid_additions\x18\v \x03(\v2\x1e.beerproto.v1.MashAcidAdditionR\x11mashAcidAdditions\x12T\n" +
	"\x14fermentation_profile\x18\f \x01(\v2!.beerproto.v1.FermentationProfileR\x13fermentationProfile\x12>\n" +
	"\fmeasurements\x18\r \x01(\v2\x1a.beerproto.v1.MeasurementsR\fmeasurements\x125\n" +
	"\testimates\x18\x0e \x01(\v2\x17.beerproto.v1.EstimatesR\testimates\x12%\n" +
	"\x04logs\x18\x0f \x03(\v2\x11.beerproto.v1.LogR\x04logs\x12\x14\n" +
	"\x05notes\x18\x10 \x01(\tR\x05notes\x12\x16\n" +
	"\x06rating\x18\x11 \x01(\x01R\x06rating\x12:\n" +
	"\n" +
	"wine_style\x18\x12 \x01(\x0e2\x1b.beerproto.v1.WineStyleTypeR\twineStyle\"\xf1\x02\n" +
	"\x10MashAcidAddition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x04acid\x18\x02 \x01(\x0e2\x16.beerproto.v1.AcidTypeR\x04acid\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x126\n" +
	"\ttarget_ph\x18\x04 \x01(\v2\x19.beerproto.v1.AcidityTypeR\btargetPh\x122\n" +
	"\afrom_ph\x18\x05 \x01(\v2\x19.beerproto.v1.AcidityTypeR\x06fromPh\x121\n" +
	"\x05basis\x18\x06 \x01(\x0e2\x1b.beerproto.v1.MashAcidBasisR\x05basis\x120\n" +
	"\x06volume\x18\a \x01(\v2\x18.beerproto.v1.VolumeTypeR\x06volume\x128\n" +
	"\tconfirmed\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tconfirmed\"\x96\x02\n" +
	"\aStarter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x05steps\x18\x02 \x03(\v2\x19.beerproto.v1.StarterStepR\x05steps\x12\x1d\n" +
	"\n" +
	"culture_id\x18\x03 \x01(\tR\tcultureId\x12:\n" +
	"\n" +
	"pitch_rate\x18\x04 \x01(\v2\x1b.beerproto.v1.PitchRateTypeR\tpitchRate\x129\n" +
	"\n" +
	"yeast_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tyeastDate\x124\n" +
	"\x05pitch\x18\x06 \x01(\v2\x1e.beerproto.v1.CulturePitchRateR\x05pitch\"\xc0\x01\n" +
	"\vStarterStep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\fstarter_size\x18\x02 \x01(\v2\x18.beerproto.v1.VolumeTypeR\vstarterSize\x123\n" +
	"\agravity\x18\x03 \x01(\v2\x19.beerproto.v1.GravityTypeR\agravity\x12/\n" +
	"\x05model\x18\x04 \x01(\x0e2\x19.beerproto.v1.GrowthModelR\x05model\"\xd1\x01\n" +
	"\bStepRate\x12(\n" +
	"\x03dme\x18\x01 \x01(\v2\x16.beerproto.v1.MassTypeR\x03dme\x12\x1f\n" +
	"\vgrowth_rate\x18\x02 \x01(\x01R\n" +
	"growthRate\x12>\n" +
	"\fending_count\x18\x03 \x01(\v2\x1b.beerproto.v1.CellCountTypeR\vendingCount\x12:\n" +
	"\n" +
	"pitch_rate\x18\x04 \x01(\v2\x1b.beerproto.v1.PitchRateTypeR\tpitchRate\"\xe8\x02\n" +
	"\x10CulturePitchRate\x12R\n" +
	"\x17target_pitch_rate_cells\x18\x01 \x01(\v2\x1b.beerproto.v1.CellCountTypeR\x14targetPitchRateCells\x12D\n" +
	"\x0fcells_available\x18\x02 \x01(\v2\x1b.beerproto.v1.CellCountTypeR\x0ecellsAvailable\x12;\n" +
	"\n" +
	"difference\x18\x03 \x01(\v2\x1b.beerproto.v1.CellCountTypeR\n" +
	"difference\x12D\n" +
	"\x10pitch_rate_as_is\x18\x04 \x01(\v2\x1b.beerproto.v1.PitchRateTypeR\rpitchRateAsIs\x127\n" +
	"\tviability\x18\x05 \x01(\v2\x19.beerproto.v1.PercentTypeR\tviability\"\xb3\x02\n" +
	"\x03Log\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\x125\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1d.beerproto.v1.BatchStatusTypeR\x06status\x123\n" +
	"\agravity\x18\x05 \x01(\v2\x19.beerproto.v1.GravityTypeR\agravity\x12?\n" +
	"\vtemperature\x18\x06 \x01(\v2\x1d.beerproto.v1.TemperatureTypeR\vtemperature\x12)\n" +
	"\x05taste\x18\a \x01(\v2\x13.beerproto.v1.TasteR\x05taste\"\x9d\x01\n" +
	"\x05Taste\x12\x16\n" +
	"\x06rating\x18\x01 \x01(\x01R\x06rating\x12\x14\n" +
	"\x05notes\x18\x02 \x01(\tR\x05notes\x12\x1e\n" +
	"\n" +
	"bitterness\x18\x03 \x01(\x01R\n" +
	"bitterness\x12\x1c\n" +
	"\tsweetness\x18\x04 \x01(\x01R\tsweetness\x12\x12\n" +
	"\x04body\x18\x05 \x01(\x01R\x04body\x12\x14\n" +
	"\x05aroma\x18\x06 \x01(\x01R\x05aroma\"\xa1\x01\n" +
	"\x13FermentationProfile\x12I\n" +
	"\x12fermentation_start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x11fermentationStart\x12?\n" +
	"\rbottling_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fbottlingDate\"\xad\x0e\n" +
	"\fMeasurements\x129\n" +
	"\vboil_volume\x18\x01 \x01(\v2\x18.beerproto.v1.VolumeTypeR\n" +
	"boilVolume\x12@\n" +
	"\x0fpre_boil_volume\x18\x02 \x01(\v2\x18.beerproto.v1.VolumeTypeR\rpreBoilVolume\x12O\n" +
	"\x17post_boil_kettle_volume\x18\x03 \x01(\v2\x18.beerproto.v1.VolumeTypeR\x14postBoilKettleVolume\x12;\n" +
	"\fbatch_volume\x18\x04 \x01(\v2\x18.beerproto.v1.VolumeTypeR\vbatchVolume\x12C\n" +
	"\x10fermenter_volume\x18\x05 \x01(\v2\x18.beerproto.v1.VolumeTypeR\x0ffermenterVolume\x12A\n" +
	"\x0ffermenter_topup\x18\x06 \x01(\v2\x18.beerproto.v1.VolumeTypeR\x0efermenterTopup\x12A\n" +
	"\x0fbottling_volume\x18\a \x01(\v2\x18.beerproto.v1.VolumeTypeR\x0ebottlingVolume\x12C\n" +
	"\x10packaging_volume\x18\b \x01(\v2\x18.beerproto.v1.VolumeTypeR\x0fpackagingVolume\x12C\n" +
	"\x11boil_off_per_hour\x18\t \x01(\v2\x18.beerproto.v1.VolumeTypeR\x0eboilOffPerHour\x12G\n" +
	"\x12first_wort_gravity\x18\n" +
	" \x01(\v2\x19.beerproto.v1.GravityTypeR\x10firstWortGravity\x12C\n" +
	"\x10pre_boil_gravity\x18\v \x01(\v2\x19.beerproto.v1.GravityTypeR\x0epreBoilGravity\x12E\n" +
	"\x11post_boil_gravity\x18\f \x01(\v2\x19.beerproto.v1.GravityTypeR\x0fpostBoilGravity\x12D\n" +
	"\x10original_gravity\x18\r \x01(\v2\x19.beerproto.v1.GravityTypeR\x0foriginalGravity\x12>\n" +
	"\rfinal_gravity\x18\x0e \x01(\v2\x19.beerproto.v1.GravityTypeR\ffinalGravity\x12N\n" +
	"\x15conversion_efficiency\x18\x0f \x01(\v2\x19.beerproto.v1.PercentTypeR\x14conversionEfficiency\x12F\n" +
	"\x11lauter_efficiency\x18\x10 \x01(\v2\x19.beerproto.v1.PercentTypeR\x10lauterEfficiency\x12B\n" +
	"\x0fmash_efficiency\x18\x11 \x01(\v2\x19.beerproto.v1.PercentTypeR\x0emashEfficiency\x12L\n" +
	"\x14brewhouse_efficiency\x18\x12 \x01(\v2\x19.beerproto.v1.PercentTypeR\x13brewhouseEfficiency\x12E\n" +
	"\x11alcohol_by_volume\x18\x13 \x01(\v2\x19.beerproto.v1.PercentTypeR\x0falcoholByVolume\x12;\n" +
	"\vattenuation\x18\x14 \x01(\v2\x19.beerproto.v1.PercentTypeR\vattenuation\x12-\n" +
	"\x05color\x18\x15 \x01(\v2\x17.beerproto.v1.ColorTypeR\x05color\x12<\n" +
	"\n" +
	"bitterness\x18\x16 \x01(\v2\x1c.beerproto.v1.BitternessTypeR\n" +
	"bitterness\x122\n" +
	"\amash_ph\x18\x17 \x01(\v2\x19.beerproto.v1.AcidityTypeR\x06mashPh\x122\n" +
	"\abeer_ph\x18\x18 \x01(\v2\x19.beerproto.v1.AcidityTypeR\x06beerPh\x123\n" +
	"\tboil_time\x18\x19 \x01(\v2\x16.beerproto.v1.TimeTypeR\bboilTime\x12V\n" +
	"\x17carbonation_temperature\x18\x1a \x01(\v2\x1d.beerproto.v1.TemperatureTypeR\x16carbonationTemperature\x12R\n" +
	"\x12titratable_acidity\x18\x1b \x01(\v2#.beerproto.v1.TitratableAcidityTypeR\x11titratableAcidity\"\xc3\x02\n" +
	"\tEstimates\x12@\n" +
	"\x0fpre_boil_volume\x18\x01 \x01(\v2\x18.beerproto.v1.VolumeTypeR\rpreBoilVolume\x12C\n" +
	"\x10pre_boil_gravity\x18\x02 \x01(\v2\x19.beerproto.v1.GravityTypeR\x0epreBoilGravity\x12<\n" +
	"\n" +
	"bitterness\x18\x03 \x01(\v2\x1c.beerproto.v1.BitternessTypeR\n" +
	"bitterness\x122\n" +
	"\amash_ph\x18\x04 \x01(\v2\x19.beerproto.v1.AcidityTypeR\x06mashPh\x12=\n" +
	"\rmash_ph_model\x18\x05 \x01(\x0e2\x19.beerproto.v1.MashPhModelR\vmashPhModel*~\n" +
	"\rWineStyleType\x12\x1f\n" +
	"\x1bWINE_STYLE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13WINE_STYLE_TYPE_RED\x10\x01\x12\x19\n" +
	"\x15WINE_STYLE_TYPE_WHITE\x10\x02\x12\x18\n" +
	"\x14WINE_STYLE_TYPE_ROSE\x10\x03*\xfa\x01\n" +
	"\x0fBatchStatusType\x12!\n" +
	"\x1dBATCH_STATUS_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aBATCH_STATUS_TYPE_PLANNING\x10\x01\x12\x1d\n" +
	"\x19BATCH_STATUS_TYPE_BREWING\x10\x02\x12 \n" +
	"\x1cBATCH_STATUS_TYPE_FERMENTING\x10\x03\x12\"\n" +
	"\x1eBATCH_STATUS_TYPE_CONDITIONING\x10\x04\x12\x1f\n" +
	"\x1bBATCH_STATUS_TYPE_COMPLETED\x10\x05\x12\x1e\n" +
	"\x1aBATCH_STATUS_TYPE_ARCHIVED\x10\x06*\xcd\x01\n" +
	"\x1bWaterAdjustmentStrategyType\x12.\n" +
	"*WATER_ADJUSTMENT_STRATEGY_TYPE_UNSPECIFIED\x10\x00\x12(\n" +
	"$WATER_ADJUSTMENT_STRATEGY_TYPE_SALTS\x10\x01\x12+\n" +
	"'WATER_ADJUSTMENT_STRATEGY_TYPE_DILUTION\x10\x02\x12'\n" +
	"#WATER_ADJUSTMENT_STRATEGY_TYPE_ACID\x10\x03*o\n" +
	"\rMashAcidBasis\x12\x1f\n" +
	"\x1bMASH_ACID_BASIS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18MASH_ACID_BASIS_ESTIMATE\x10\x01\x12\x1f\n" +
	"\x1bMASH_ACID_BASIS_MEASUREMENT\x10\x02*\x91\x01\n" +
	"\vGrowthModel\x12\x1c\n" +
	"\x18GROWTH_MODEL_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17GROWTH_MODEL_BRAUKAISER\x10\x01\x12%\n" +
	"!GROWTH_MODEL_C_WHITE_NO_AGITATION\x10\x02\x12 \n" +
	"\x1cGROWTH_MODEL_C_WHITE_SHAKING\x10\x03B\xab\x01\n" +
	"\x10com.beerproto.v1B\n" +
	"BatchProtoP\x01Z:github.com/beerproto/beerproto_go/beerproto/v1;beerprotov1\xa2\x02\x03BXX\xaa\x02\fBeerproto.V1\xca\x02\fBeerproto\\V1\xe2\x02\x18Beerproto\\V1\\GPBMetadata\xea\x02\rBeerproto::V1b\x06proto3"

var (
	file_beerproto_v1_batch_proto_rawDescOnce sync.Once
	file_beerproto_v1_batch_proto_rawDescData []byte
)

func file_beerproto_v1_batch_proto_rawDescGZIP() []byte {
	file_beerproto_v1_batch_proto_rawDescOnce.Do(func() {
		file_beerproto_v1_batch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beerproto_v1_batch_proto_rawDesc), len(file_beerproto_v1_batch_proto_rawDesc)))
	})
	return file_beerproto_v1_batch_proto_rawDescData
}

var file_beerproto_v1_batch_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_beerproto_v1_batch_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_beerproto_v1_batch_proto_goTypes = []any{
	(WineStyleType)(0),               // 0: beerproto.v1.WineStyleType
	(BatchStatusType)(0),             // 1: beerproto.v1.BatchStatusType
	(WaterAdjustmentStrategyType)(0), // 2: beerproto.v1.WaterAdjustmentStrategyType
	(MashAcidBasis)(0),               // 3: beerproto.v1.MashAcidBasis
	(GrowthModel)(0),                 // 4: beerproto.v1.GrowthModel
	(*Batch)(nil),                    // 5: beerproto.v1.Batch
	(*MashAcidAddition)(nil),         // 6: beerproto.v1.MashAcidAddition
	(*Starter)(nil),                  // 7: beerproto.v1.Starter
	(*StarterStep)(nil),              // 8: beerproto.v1.StarterStep
	(*StepRate)(nil),                 // 9: beerproto.v1.StepRate
	(*CulturePitchRate)(nil),         // 10: beerproto.v1.CulturePitchRate
	(*Log)(nil),                      // 11: beerproto.v1.Log
	(*Taste)(nil),                    // 12: beerproto.v1.Taste
	(*FermentationProfile)(nil),      // 13: beerproto.v1.FermentationProfile
	(*Measurements)(nil),             // 14: beerproto.v1.Measurements
	(*Estimates)(nil),                // 15: beerproto.v1.Estimates
	(*timestamppb.Timestamp)(nil),    // 16: google.protobuf.Timestamp
	(*EquipmentType)(nil),            // 17: beerproto.v1.EquipmentType
	(AcidType)(0),                    // 18: beerproto.v1.AcidType
	(*AcidityType)(nil),              // 19: beerproto.v1.AcidityType
	(*VolumeType)(nil),               // 20: beerproto.v1.VolumeType
	(*PitchRateType)(nil),            // 21: beerproto.v1.PitchRateType
	(*GravityType)(nil),              // 22: beerproto.v1.GravityType
	(*MassType)(nil),                 // 23: beerproto.v1.MassType
	(*CellCountType)(nil),            // 24: beerproto.v1.CellCountType
	(*PercentType)(nil),              // 25: beerproto.v1.PercentType
	(*TemperatureType)(nil),          // 26: beerproto.v1.TemperatureType
	(*ColorType)(nil),                // 27: beerproto.v1.ColorType
	(*BitternessType)(nil),           // 28: beerproto.v1.BitternessType
	(*TimeType)(nil),                 // 29: beerproto.v1.TimeType
	(*TitratableAcidityType)(nil),    // 30: beerproto.v1.TitratableAcidityType
	(MashPhModel)(0),                 // 31: beerproto.v1.MashPhModel
}
var file_beerproto_v1_batch_proto_depIdxs = []int32{
	16, // 0: beerproto.v1.Batch.date:type_name -> google.protobuf.Timestamp
	1,  // 1: beerproto.v1.Batch.status:type_name -> beerproto.v1.BatchStatusType
	17, // 2: beerproto.v1.Batch.equipment:type_name -> beerproto.v1.EquipmentType
	7,  // 3: beerproto.v1.Batch.starters:type_name -> beerproto.v1.Starter
	2,  // 4: beerproto.v1.Batch.water_adjustment_strategy:type_name -> beerproto.v1.WaterAdjustmentStrategyType
	6,  // 5: beerproto.v1.Batch.mash_acid_additions:type_name -> beerproto.v1.MashAcidAddition
	13, // 6: beerproto.v1.Batch.fermentation_profile:type_name -> beerproto.v1.FermentationProfile
	14, // 7: beerproto.v1.Batch.measurements:type_name -> beerproto.v1.Measurements
	15, // 8: beerproto.v1.Batch.estimates:type_name -> beerproto.v1.Estimates
	11, // 9: beerproto.v1.Batch.logs:type_name -> beerproto.v1.Log
	0,  // 10: beerproto.v1.Batch.wine_style:type_name -> beerproto.v1.WineStyleType
	18, // 11: beerproto.v1.MashAcidAddition.acid:type_name -> beerproto.v1.AcidType
	19, // 12: beerproto.v1.MashAcidAddition.target_ph:type_name -> beerproto.v1.AcidityType
	19, // 13: beerproto.v1.MashAcidAddition.from_ph:type_name -> beerproto.v1.AcidityType
	3,  // 14: beerproto.v1.MashAcidAddition.basis:type_name -> beerproto.v1.MashAcidBasis
	20, // 15: beerproto.v1.MashAcidAddition.volume:type_name -> beerproto.v1.VolumeType
	16, // 16: beerproto.v1.MashAcidAddition.confirmed:type_name -> google.protobuf.Timestamp
	8,  // 17: beerproto.v1.Starter.steps:type_name -> beerproto.v1.StarterStep
	21, // 18: beerproto.v1.Starter.pitch_rate:type_name -> beerproto.v1.PitchRateType
	16, // 19: beerproto.v1.Starter.yeast_date:type_name -> google.protobuf.Timestamp
	10, // 20: beerproto.v1.Starter.pitch:type_name -> beerproto.v1.CulturePitchRate
	20, // 21: beerproto.v1.StarterStep.starter_size:type_name -> beerproto.v1.VolumeType
	22, // 22: beerproto.v1.StarterStep.gravity:type_name -> beerproto.v1.GravityType
	4,  // 23: beerproto.v1.StarterStep.model:type_name -> beerproto.v1.GrowthModel
	23, // 24: beerproto.v1.StepRate.dme:type_name -> beerproto.v1.MassType
	24, // 25: beerproto.v1.StepRate.ending_count:type_name -> beerproto.v1.CellCountType
	21, // 26: beerproto.v1.StepRate.pitch_rate:type_name -> beerproto.v1.PitchRateType
	24, // 27: beerproto.v1.CulturePitchRate.target_pitch_rate_cells:type_name -> beerproto.v1.CellCountType
	24, // 28: beerproto.v1.CulturePitchRate.cells_available:type_name -> beerproto.v1.CellCountType
	24, // 29: beerproto.v1.CulturePitchRate.difference:type_name -> beerproto.v1.CellCountType
	21, // 30: beerproto.v1.CulturePitchRate.pitch_rate_as_is:type_name -> beerproto.v1.PitchRateType
	25, // 31: beerproto.v1.CulturePitchRate.viability:type_name -> beerproto.v1.PercentType
	16, // 32: beerproto.v1.Log.date:type_name -> google.protobuf.Timestamp
	1,  // 33: beerproto.v1.Log.status:type_name -> beerproto.v1.BatchStatusType
	22, // 34: beerproto.v1.Log.gravity:type_name -> beerproto.v1.GravityType
	26, // 35: beerproto.v1.Log.temperature:type_name -> beerproto.v1.TemperatureType
	12, // 36: beerproto.v1.Log.taste:type_name -> beerproto.v1.Taste
	16, // 37: beerproto.v1.FermentationProfile.fermentation_start:type_name -> google.protobuf.Timestamp
	16, // 38: beerproto.v1.FermentationProfile.bottling_date:type_name -> google.protobuf.Timestamp
	20, // 39: beerproto.v1.Measurements.boil_volume:type_name -> beerproto.v1.VolumeType
	20, // 40: beerproto.v1.Measurements.pre_boil_volume:type_name -> beerproto.v1.VolumeType
	20, // 41: beerproto.v1.Measurements.post_boil_kettle_volume:type_name -> beerproto.v1.VolumeType
	20, // 42: beerproto.v1.Measurements.batch_volume:type_name -> beerproto.v1.VolumeType
	20, // 43: beerproto.v1.Measurements.fermenter_volume:type_name -> beerproto.v1.VolumeType
	20, // 44: beerproto.v1.Measurements.fermenter_topup:type_name -> beerproto.v1.VolumeType
	20, // 45: beerproto.v1.Measurements.bottling_volume:type_name -> beerproto.v1.VolumeType
	20, // 46: beerproto.v1.Measurements.packaging_volume:type_name -> beerproto.v1.VolumeType
	20, // 47: beerproto.v1.Measurements.boil_off_per_hour:type_name -> beerproto.v1.VolumeType
	22, // 48: beerproto.v1.Measurements.first_wort_gravity:type_name -> beerproto.v1.GravityType
	22, // 49: beerproto.v1.Measurements.pre_boil_gravity:type_name -> beerproto.v1.GravityType
	22, // 50: beerproto.v1.Measurements.post_boil_gravity:type_name -> beerproto.v1.GravityType
	22, // 51: beerproto.v1.Measurements.original_gravity:type_name -> beerproto.v1.GravityType
	22, // 52: beerproto.v1.Measurements.final_gravity:type_name -> beerproto.v1.GravityType
	25, // 53: beerproto.v1.Measurements.conversion_efficiency:type_name -> beerproto.v1.PercentType
	25, // 54: beerproto.v1.Measurements.lauter_efficiency:type_name -> beerproto.v1.PercentType
	25, // 55: beerproto.v1.Measurements.mash_efficiency:type_name -> beerproto.v1.PercentType
	25, // 56: beerproto.v1.Measurements.brewhouse_efficiency:type_name -> beerproto.v1.PercentType
	25, // 57: beerproto.v1.Measurements.alcohol_by_volume:type_name -> beerproto.v1.PercentType
	25, // 58: beerproto.v1.Measurements.attenuation:type_name -> beerproto.v1.PercentType
	27, // 59: beerproto.v1.Measurements.color:type_name -> beerproto.v1.ColorType
	28, // 60: beerproto.v1.Measurements.bitterness:type_name -> beerproto.v1.BitternessType
	19, // 61: beerproto.v1.Measurements.mash_ph:type_name -> beerproto.v1.AcidityType
	19, // 62: beerproto.v1.Measurements.beer_ph:type_name -> beerproto.v1.AcidityType
	29, // 63: beerproto.v1.Measurements.boil_time:type_name -> beerproto.v1.TimeType
	26, // 64: beerproto.v1.Measurements.carbonation_temperature:type_name -> beerproto.v1.TemperatureType
	30, // 65: beerproto.v1.Measurements.titratable_acidity:type_name -> beerproto.v1.TitratableAcidityType
	20, // 66: beerproto.v1.Estimates.pre_boil_volume:type_name -> beerproto.v1.VolumeType
	22, // 67: beerproto.v1.Estimates.pre_boil_gravity:type_name -> beerproto.v1.GravityType
	28, // 68: beerproto.v1.Estimates.bitterness:type_name -> beerproto.v1.BitternessType
	19, // 69: beerproto.v1.Estimates.mash_ph:type_name -> beerproto.v1.AcidityType
	31, // 70: beerproto.v1.Estimates.mash_ph_model:type_name -> beerproto.v1.MashPhModel
	71, // [71:71] is the sub-list for method output_type
	71, // [71:71] is the sub-list for method input_type
	71, // [71:71] is the sub-list for extension type_name
	71, // [71:71] is the sub-list for extension extendee
	0,  // [0:71] is the sub-list for field type_name
}

func init() { file_beerproto_v1_batch_proto_init() }
func file_beerproto_v1_batch_proto_init() {
	if File_beerproto_v1_batch_proto != nil {
		return
	}
	file_beerproto_v1_equipment_proto_init()
	file_beerproto_v1_measureable_units_proto_init()
	file_beerproto_v1_water_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beerproto_v1_batch_proto_rawDesc), len(file_beerproto_v1_batch_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_beerproto_v1_batch_proto_goTypes,
		DependencyIndexes: file_beerproto_v1_batch_proto_depIdxs,
		EnumInfos:         file_beerproto_v1_batch_proto_enumTypes,
		MessageInfos:      file_beerproto_v1_batch_proto_msgTypes,
	}.Build()
	File_beerproto_v1_batch_proto = out.File
	file_beerproto_v1_batch_proto_goTypes = nil
	file_beerproto_v1_batch_proto_depIdxs = nil
}
