//*
// BeerProto
//
// Another beer format, written in protocol buffer.
//
// Copyright (c) 2020 Ross Merrigan

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: beerproto/v1/boil.proto

package beerprotov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BoilProcedureType defines the procedure for performing a boil. A boil procedure with no steps is the same as a standard single step boil
type BoilProcedureType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PreBoilSize   *VolumeType            `protobuf:"bytes,2,opt,name=pre_boil_size,json=preBoilSize,proto3" json:"pre_boil_size,omitempty"`
	BoilTime      *TimeType              `protobuf:"bytes,3,opt,name=boil_time,json=boilTime,proto3" json:"boil_time,omitempty"`
	BoilSteps     []*BoilStepType        `protobuf:"bytes,4,rep,name=boil_steps,json=boilSteps,proto3" json:"boil_steps,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Notes         string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoilProcedureType) Reset() {
	*x = BoilProcedureType{}
	mi := &file_beerproto_v1_boil_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoilProcedureType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoilProcedureType) ProtoMessage() {}

func (x *BoilProcedureType) ProtoReflect() protoreflect.Message {
	mi := &file_beerproto_v1_boil_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoilProcedureType.ProtoReflect.Descriptor instead.
func (*BoilProcedureType) Descriptor() ([]byte, []int) {
	return file_beerproto_v1_boil_proto_rawDescGZIP(), []int{0}
}

func (x *BoilProcedureType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BoilProcedureType) GetPreBoilSize() *VolumeType {
	if x != nil {
		return x.PreBoilSize
	}
	return nil
}

func (x *BoilProcedureType) GetBoilTime() *TimeType {
	if x != nil {
		return x.BoilTime
	}
	return nil
}

func (x *BoilProcedureType) GetBoilSteps() []*BoilStepType {
	if x != nil {
		return x.BoilSteps
	}
	return nil
}

func (x *BoilProcedureType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BoilProcedureType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BoilProcedureType) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

var File_beerproto_v1_boil_proto protoreflect.FileDescriptor

const file_beerproto_v1_boil_proto_rawDesc = "" +
	"\n" +
	"\x17beerproto/v1/boil.proto\x12\fbeerproto.v1\x1a\x1cbeerproto/v1/boil_step.proto\x1a$beerproto/v1/measureable_units.proto\x1a\x1bbuf/validate/validate.proto\"\xb2\x02\n" +
	"\x11BoilProcedureType\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\x12<\n" +
	"\rpre_boil_size\x18\x02 \x01(\v2\x18.beerproto.v1.VolumeTypeR\vpreBoilSize\x12;\n" +
	"\tboil_time\x18\x03 \x01(\v2\x16.beerproto.v1.TimeTypeB\x06\xbaH\x03\xc8\x01\x01R\bboilTime\x129\n" +
	"\n" +
	"boil_steps\x18\x04 \x03(\v2\x1a.beerproto.v1.BoilStepTypeR\tboilSteps\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notesB\xaa\x01\n" +
	"\x10com.beerproto.v1B\tBoilProtoP\x01Z:github.com/beerproto/beerproto_go/beerproto/v1;beerprotov1\xa2\x02\x03BXX\xaa\x02\fBeerproto.V1\xca\x02\fBeerproto\\V1\xe2\x02\x18Beerproto\\V1\\GPBMetadata\xea\x02\rBeerproto::V1b\x06proto3"

var (
	file_beerproto_v1_boil_proto_rawDescOnce sync.Once
	file_beerproto_v1_boil_proto_rawDescData []byte
)

func file_beerproto_v1_boil_proto_rawDescGZIP() []byte {
	file_beerproto_v1_boil_proto_rawDescOnce.Do(func() {
		file_beerproto_v1_boil_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beerproto_v1_boil_proto_rawDesc), len(file_beerproto_v1_boil_proto_rawDesc)))
	})
	return file_beerproto_v1_boil_proto_rawDescData
}

var file_beerproto_v1_boil_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_beerproto_v1_boil_proto_goTypes = []any{
	(*BoilProcedureType)(nil), // 0: beerproto.v1.BoilProcedureType
	(*VolumeType)(nil),        // 1: beerproto.v1.VolumeType
	(*TimeType)(nil),          // 2: beerproto.v1.TimeType
	(*BoilStepType)(nil),      // 3: beerproto.v1.BoilStepType
}
var file_beerproto_v1_boil_proto_depIdxs = []int32{
	1, // 0: beerproto.v1.BoilProcedureType.pre_boil_size:type_name -> beerproto.v1.VolumeType
	2, // 1: beerproto.v1.BoilProcedureType.boil_time:type_name -> beerproto.v1.TimeType
	3, // 2: beerproto.v1.BoilProcedureType.boil_steps:type_name -> beerproto.v1.BoilStepType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_beerproto_v1_boil_proto_init() }
func file_beerproto_v1_boil_proto_init() {
	if File_beerproto_v1_boil_proto != nil {
		return
	}
	file_beerproto_v1_boil_step_proto_init()
	file_beerproto_v1_measureable_units_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beerproto_v1_boil_proto_rawDesc), len(file_beerproto_v1_boil_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_beerproto_v1_boil_proto_goTypes,
		DependencyIndexes: file_beerproto_v1_boil_proto_depIdxs,
		MessageInfos:      file_beerproto_v1_boil_proto_msgTypes,
	}.Build()
	File_beerproto_v1_boil_proto = out.File
	file_beerproto_v1_boil_proto_goTypes = nil
	file_beerproto_v1_boil_proto_depIdxs = nil
}
