//*
// BeerProto
//
// Another beer format, written in protocol buffer.
//
// Copyright (c) 2020 Ross Merrigan

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: beerproto/v1/packaging_graphic.proto

package beerprotov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackagingGraphicType_PositionUnit int32

const (
	PackagingGraphicType_POSITION_UNIT_UNSPECIFIED      PackagingGraphicType_PositionUnit = 0
	PackagingGraphicType_POSITION_UNIT_BODY_FRONT       PackagingGraphicType_PositionUnit = 1
	PackagingGraphicType_POSITION_UNIT_BODY_BACK        PackagingGraphicType_PositionUnit = 2
	PackagingGraphicType_POSITION_UNIT_BODY_WRAP_AROUND PackagingGraphicType_PositionUnit = 3
	PackagingGraphicType_POSITION_UNIT_NECK_FRONT       PackagingGraphicType_PositionUnit = 4
	PackagingGraphicType_POSITION_UNIT_NECK_BACK        PackagingGraphicType_PositionUnit = 5
	PackagingGraphicType_POSITION_UNIT_NECK_WRAP_AROUND PackagingGraphicType_PositionUnit = 6
	PackagingGraphicType_POSITION_UNIT_CAP              PackagingGraphicType_PositionUnit = 7
	PackagingGraphicType_POSITION_UNIT_CARRIER          PackagingGraphicType_PositionUnit = 8
)

// Enum value maps for PackagingGraphicType_PositionUnit.
var (
	PackagingGraphicType_PositionUnit_name = map[int32]string{
		0: "POSITION_UNIT_UNSPECIFIED",
		1: "POSITION_UNIT_BODY_FRONT",
		2: "POSITION_UNIT_BODY_BACK",
		3: "POSITION_UNIT_BODY_WRAP_AROUND",
		4: "POSITION_UNIT_NECK_FRONT",
		5: "POSITION_UNIT_NECK_BACK",
		6: "POSITION_UNIT_NECK_WRAP_AROUND",
		7: "POSITION_UNIT_CAP",
		8: "POSITION_UNIT_CARRIER",
	}
	PackagingGraphicType_PositionUnit_value = map[string]int32{
		"POSITION_UNIT_UNSPECIFIED":      0,
		"POSITION_UNIT_BODY_FRONT":       1,
		"POSITION_UNIT_BODY_BACK":        2,
		"POSITION_UNIT_BODY_WRAP_AROUND": 3,
		"POSITION_UNIT_NECK_FRONT":       4,
		"POSITION_UNIT_NECK_BACK":        5,
		"POSITION_UNIT_NECK_WRAP_AROUND": 6,
		"POSITION_UNIT_CAP":              7,
		"POSITION_UNIT_CARRIER":          8,
	}
)

func (x PackagingGraphicType_PositionUnit) Enum() *PackagingGraphicType_PositionUnit {
	p := new(PackagingGraphicType_PositionUnit)
	*p = x
	return p
}

func (x PackagingGraphicType_PositionUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackagingGraphicType_PositionUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_beerproto_v1_packaging_graphic_proto_enumTypes[0].Descriptor()
}

func (PackagingGraphicType_PositionUnit) Type() protoreflect.EnumType {
	return &file_beerproto_v1_packaging_graphic_proto_enumTypes[0]
}

func (x PackagingGraphicType_PositionUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackagingGraphicType_PositionUnit.Descriptor instead.
func (PackagingGraphicType_PositionUnit) EnumDescriptor() ([]byte, []int) {
	return file_beerproto_v1_packaging_graphic_proto_rawDescGZIP(), []int{0, 0}
}

type PackagingGraphicType_GraphicType int32

const (
	PackagingGraphicType_GRAPHIC_TYPE_UNSPECIFIED PackagingGraphicType_GraphicType = 0
	PackagingGraphicType_GRAPHIC_TYPE_SVG         PackagingGraphicType_GraphicType = 1
	PackagingGraphicType_GRAPHIC_TYPE_SVGZ        PackagingGraphicType_GraphicType = 2
	PackagingGraphicType_GRAPHIC_TYPE_AI          PackagingGraphicType_GraphicType = 3
	PackagingGraphicType_GRAPHIC_TYPE_CDR         PackagingGraphicType_GraphicType = 4
	PackagingGraphicType_GRAPHIC_TYPE_CDX         PackagingGraphicType_GraphicType = 5
	PackagingGraphicType_GRAPHIC_TYPE_ODG         PackagingGraphicType_GraphicType = 6
	PackagingGraphicType_GRAPHIC_TYPE_EPS         PackagingGraphicType_GraphicType = 7
	PackagingGraphicType_GRAPHIC_TYPE_PDF         PackagingGraphicType_GraphicType = 8
	PackagingGraphicType_GRAPHIC_TYPE_PNG         PackagingGraphicType_GraphicType = 9
	PackagingGraphicType_GRAPHIC_TYPE_JPG         PackagingGraphicType_GraphicType = 10
	PackagingGraphicType_GRAPHIC_TYPE_GIF         PackagingGraphicType_GraphicType = 11
)

// Enum value maps for PackagingGraphicType_GraphicType.
var (
	PackagingGraphicType_GraphicType_name = map[int32]string{
		0:  "GRAPHIC_TYPE_UNSPECIFIED",
		1:  "GRAPHIC_TYPE_SVG",
		2:  "GRAPHIC_TYPE_SVGZ",
		3:  "GRAPHIC_TYPE_AI",
		4:  "GRAPHIC_TYPE_CDR",
		5:  "GRAPHIC_TYPE_CDX",
		6:  "GRAPHIC_TYPE_ODG",
		7:  "GRAPHIC_TYPE_EPS",
		8:  "GRAPHIC_TYPE_PDF",
		9:  "GRAPHIC_TYPE_PNG",
		10: "GRAPHIC_TYPE_JPG",
		11: "GRAPHIC_TYPE_GIF",
	}
	PackagingGraphicType_GraphicType_value = map[string]int32{
		"GRAPHIC_TYPE_UNSPECIFIED": 0,
		"GRAPHIC_TYPE_SVG":         1,
		"GRAPHIC_TYPE_SVGZ":        2,
		"GRAPHIC_TYPE_AI":          3,
		"GRAPHIC_TYPE_CDR":         4,
		"GRAPHIC_TYPE_CDX":         5,
		"GRAPHIC_TYPE_ODG":         6,
		"GRAPHIC_TYPE_EPS":         7,
		"GRAPHIC_TYPE_PDF":         8,
		"GRAPHIC_TYPE_PNG":         9,
		"GRAPHIC_TYPE_JPG":         10,
		"GRAPHIC_TYPE_GIF":         11,
	}
)

func (x PackagingGraphicType_GraphicType) Enum() *PackagingGraphicType_GraphicType {
	p := new(PackagingGraphicType_GraphicType)
	*p = x
	return p
}

func (x PackagingGraphicType_GraphicType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackagingGraphicType_GraphicType) Descriptor() protoreflect.EnumDescriptor {
	return file_beerproto_v1_packaging_graphic_proto_enumTypes[1].Descriptor()
}

func (PackagingGraphicType_GraphicType) Type() protoreflect.EnumType {
	return &file_beerproto_v1_packaging_graphic_proto_enumTypes[1]
}

func (x PackagingGraphicType_GraphicType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackagingGraphicType_GraphicType.Descriptor instead.
func (PackagingGraphicType_GraphicType) EnumDescriptor() ([]byte, []int) {
	return file_beerproto_v1_packaging_graphic_proto_rawDescGZIP(), []int{0, 1}
}

type PackagingGraphicType_UnitsType int32

const (
	PackagingGraphicType_UNITS_TYPE_UNSPECIFIED PackagingGraphicType_UnitsType = 0
	PackagingGraphicType_UNITS_TYPE_MM          PackagingGraphicType_UnitsType = 1
	PackagingGraphicType_UNITS_TYPE_IN          PackagingGraphicType_UnitsType = 2
)

// Enum value maps for PackagingGraphicType_UnitsType.
var (
	PackagingGraphicType_UnitsType_name = map[int32]string{
		0: "UNITS_TYPE_UNSPECIFIED",
		1: "UNITS_TYPE_MM",
		2: "UNITS_TYPE_IN",
	}
	PackagingGraphicType_UnitsType_value = map[string]int32{
		"UNITS_TYPE_UNSPECIFIED": 0,
		"UNITS_TYPE_MM":          1,
		"UNITS_TYPE_IN":          2,
	}
)

func (x PackagingGraphicType_UnitsType) Enum() *PackagingGraphicType_UnitsType {
	p := new(PackagingGraphicType_UnitsType)
	*p = x
	return p
}

func (x PackagingGraphicType_UnitsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackagingGraphicType_UnitsType) Descriptor() protoreflect.EnumDescriptor {
	return file_beerproto_v1_packaging_graphic_proto_enumTypes[2].Descriptor()
}

func (PackagingGraphicType_UnitsType) Type() protoreflect.EnumType {
	return &file_beerproto_v1_packaging_graphic_proto_enumTypes[2]
}

func (x PackagingGraphicType_UnitsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackagingGraphicType_UnitsType.Descriptor instead.
func (PackagingGraphicType_UnitsType) EnumDescriptor() ([]byte, []int) {
	return file_beerproto_v1_packaging_graphic_proto_rawDescGZIP(), []int{0, 2}
}

// Representation of a graphic to be placed on a vessel.
type PackagingGraphicType struct {
	state    protoimpl.MessageState            `protogen:"open.v1"`
	Position PackagingGraphicType_PositionUnit `protobuf:"varint,1,opt,name=position,proto3,enum=beerproto.v1.PackagingGraphicType_PositionUnit" json:"position,omitempty"`
	// File type
	Type PackagingGraphicType_GraphicType `protobuf:"varint,2,opt,name=type,proto3,enum=beerproto.v1.PackagingGraphicType_GraphicType" json:"type,omitempty"`
	// Base64 encoded file.
	Base64Data string `protobuf:"bytes,3,opt,name=base64_data,json=base64Data,proto3" json:"base64_data,omitempty"`
	// URLS to hosted version of image.
	Urls []string `protobuf:"bytes,4,rep,name=urls,proto3" json:"urls,omitempty"`
	// Dots per inch.
	Dpi    int32 `protobuf:"varint,5,opt,name=dpi,proto3" json:"dpi,omitempty"`
	Width  int64 `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Height int64 `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	// The unit type which are used for measurements.
	Units         PackagingGraphicType_UnitsType `protobuf:"varint,8,opt,name=units,proto3,enum=beerproto.v1.PackagingGraphicType_UnitsType" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackagingGraphicType) Reset() {
	*x = PackagingGraphicType{}
	mi := &file_beerproto_v1_packaging_graphic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackagingGraphicType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackagingGraphicType) ProtoMessage() {}

func (x *PackagingGraphicType) ProtoReflect() protoreflect.Message {
	mi := &file_beerproto_v1_packaging_graphic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackagingGraphicType.ProtoReflect.Descriptor instead.
func (*PackagingGraphicType) Descriptor() ([]byte, []int) {
	return file_beerproto_v1_packaging_graphic_proto_rawDescGZIP(), []int{0}
}

func (x *PackagingGraphicType) GetPosition() PackagingGraphicType_PositionUnit {
	if x != nil {
		return x.Position
	}
	return PackagingGraphicType_POSITION_UNIT_UNSPECIFIED
}

func (x *PackagingGraphicType) GetType() PackagingGraphicType_GraphicType {
	if x != nil {
		return x.Type
	}
	return PackagingGraphicType_GRAPHIC_TYPE_UNSPECIFIED
}

func (x *PackagingGraphicType) GetBase64Data() string {
	if x != nil {
		return x.Base64Data
	}
	return ""
}

func (x *PackagingGraphicType) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *PackagingGraphicType) GetDpi() int32 {
	if x != nil {
		return x.Dpi
	}
	return 0
}

func (x *PackagingGraphicType) GetWidth() int64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *PackagingGraphicType) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PackagingGraphicType) GetUnits() PackagingGraphicType_UnitsType {
	if x != nil {
		return x.Units
	}
	return PackagingGraphicType_UNITS_TYPE_UNSPECIFIED
}

var File_beerproto_v1_packaging_graphic_proto protoreflect.FileDescriptor

const file_beerproto_v1_packaging_graphic_proto_rawDesc = "" +
	"\n" +
	"$beerproto/v1/packaging_graphic.proto\x12\fbeerproto.v1\"\xef\a\n" +
	"\x14PackagingGraphicType\x12K\n" +
	"\bposition\x18\x01 \x01(\x0e2/.beerproto.v1.PackagingGraphicType.PositionUnitR\bposition\x12B\n" +
	"\x04type\x18\x02 \x01(\x0e2..beerproto.v1.PackagingGraphicType.GraphicTypeR\x04type\x12\x1f\n" +
	"\vbase64_data\x18\x03 \x01(\tR\n" +
	"base64Data\x12\x12\n" +
	"\x04urls\x18\x04 \x03(\tR\x04urls\x12\x10\n" +
	"\x03dpi\x18\x05 \x01(\x05R\x03dpi\x12\x14\n" +
	"\x05width\x18\x06 \x01(\x03R\x05width\x12\x16\n" +
	"\x06height\x18\a \x01(\x03R\x06height\x12B\n" +
	"\x05units\x18\b \x01(\x0e2,.beerproto.v1.PackagingGraphicType.UnitsTypeR\x05units\"\x9d\x02\n" +
	"\fPositionUnit\x12\x1d\n" +
	"\x19POSITION_UNIT_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18POSITION_UNIT_BODY_FRONT\x10\x01\x12\x1b\n" +
	"\x17POSITION_UNIT_BODY_BACK\x10\x02\x12\"\n" +
	"\x1ePOSITION_UNIT_BODY_WRAP_AROUND\x10\x03\x12\x1c\n" +
	"\x18POSITION_UNIT_NECK_FRONT\x10\x04\x12\x1b\n" +
	"\x17POSITION_UNIT_NECK_BACK\x10\x05\x12\"\n" +
	"\x1ePOSITION_UNIT_NECK_WRAP_AROUND\x10\x06\x12\x15\n" +
	"\x11POSITION_UNIT_CAP\x10\a\x12\x19\n" +
	"\x15POSITION_UNIT_CARRIER\x10\b\"\x9d\x02\n" +
	"\vGraphicType\x12\x1c\n" +
	"\x18GRAPHIC_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10GRAPHIC_TYPE_SVG\x10\x01\x12\x15\n" +
	"\x11GRAPHIC_TYPE_SVGZ\x10\x02\x12\x13\n" +
	"\x0fGRAPHIC_TYPE_AI\x10\x03\x12\x14\n" +
	"\x10GRAPHIC_TYPE_CDR\x10\x04\x12\x14\n" +
	"\x10GRAPHIC_TYPE_CDX\x10\x05\x12\x14\n" +
	"\x10GRAPHIC_TYPE_ODG\x10\x06\x12\x14\n" +
	"\x10GRAPHIC_TYPE_EPS\x10\a\x12\x14\n" +
	"\x10GRAPHIC_TYPE_PDF\x10\b\x12\x14\n" +
	"\x10GRAPHIC_TYPE_PNG\x10\t\x12\x14\n" +
	"\x10GRAPHIC_TYPE_JPG\x10\n" +
	"\x12\x14\n" +
	"\x10GRAPHIC_TYPE_GIF\x10\v\"M\n" +
	"\tUnitsType\x12\x1a\n" +
	"\x16UNITS_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rUNITS_TYPE_MM\x10\x01\x12\x11\n" +
	"\rUNITS_TYPE_IN\x10\x02B\xb6\x01\n" +
	"\x10com.beerproto.v1B\x15PackagingGraphicProtoP\x01Z:github.com/beerproto/beerproto_go/beerproto/v1;beerprotov1\xa2\x02\x03BXX\xaa\x02\fBeerproto.V1\xca\x02\fBeerproto\\V1\xe2\x02\x18Beerproto\\V1\\GPBMetadata\xea\x02\rBeerproto::V1b\x06proto3"

var (
	file_beerproto_v1_packaging_graphic_proto_rawDescOnce sync.Once
	file_beerproto_v1_packaging_graphic_proto_rawDescData []byte
)

func file_beerproto_v1_packaging_graphic_proto_rawDescGZIP() []byte {
	file_beerproto_v1_packaging_graphic_proto_rawDescOnce.Do(func() {
		file_beerproto_v1_packaging_graphic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beerproto_v1_packaging_graphic_proto_rawDesc), len(file_beerproto_v1_packaging_graphic_proto_rawDesc)))
	})
	return file_beerproto_v1_packaging_graphic_proto_rawDescData
}

var file_beerproto_v1_packaging_graphic_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_beerproto_v1_packaging_graphic_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_beerproto_v1_packaging_graphic_proto_goTypes = []any{
	(PackagingGraphicType_PositionUnit)(0), // 0: beerproto.v1.PackagingGraphicType.PositionUnit
	(PackagingGraphicType_GraphicType)(0),  // 1: beerproto.v1.PackagingGraphicType.GraphicType
	(PackagingGraphicType_UnitsType)(0),    // 2: beerproto.v1.PackagingGraphicType.UnitsType
	(*PackagingGraphicType)(nil),           // 3: beerproto.v1.PackagingGraphicType
}
var file_beerproto_v1_packaging_graphic_proto_depIdxs = []int32{
	0, // 0: beerproto.v1.PackagingGraphicType.position:type_name -> beerproto.v1.PackagingGraphicType.PositionUnit
	1, // 1: beerproto.v1.PackagingGraphicType.type:type_name -> beerproto.v1.PackagingGraphicType.GraphicType
	2, // 2: beerproto.v1.PackagingGraphicType.units:type_name -> beerproto.v1.PackagingGraphicType.UnitsType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_beerproto_v1_packaging_graphic_proto_init() }
func file_beerproto_v1_packaging_graphic_proto_init() {
	if File_beerproto_v1_packaging_graphic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beerproto_v1_packaging_graphic_proto_rawDesc), len(file_beerproto_v1_packaging_graphic_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_beerproto_v1_packaging_graphic_proto_goTypes,
		DependencyIndexes: file_beerproto_v1_packaging_graphic_proto_depIdxs,
		EnumInfos:         file_beerproto_v1_packaging_graphic_proto_enumTypes,
		MessageInfos:      file_beerproto_v1_packaging_graphic_proto_msgTypes,
	}.Build()
	File_beerproto_v1_packaging_graphic_proto = out.File
	file_beerproto_v1_packaging_graphic_proto_goTypes = nil
	file_beerproto_v1_packaging_graphic_proto_depIdxs = nil
}
