//*
// BeerProto
//
// Another beer format, written in protocol buffer.
//
// Copyright (c) 2020 Ross Merrigan

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: beerproto/v1/srm.proto

package beerprotov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SRM int32

const (
	SRM_SRM_UNSPECIFIED SRM = 0
	SRM_SRM_1           SRM = 1
	SRM_SRM_2           SRM = 2
	SRM_SRM_3           SRM = 3
	SRM_SRM_4           SRM = 4
	SRM_SRM_5           SRM = 5
	SRM_SRM_6           SRM = 6
	SRM_SRM_7           SRM = 7
	SRM_SRM_8           SRM = 8
	SRM_SRM_9           SRM = 9
	SRM_SRM_10          SRM = 10
	SRM_SRM_11          SRM = 11
	SRM_SRM_12          SRM = 12
	SRM_SRM_13          SRM = 13
	SRM_SRM_14          SRM = 14
	SRM_SRM_15          SRM = 15
	SRM_SRM_16          SRM = 16
	SRM_SRM_17          SRM = 17
	SRM_SRM_18          SRM = 18
	SRM_SRM_19          SRM = 19
	SRM_SRM_20          SRM = 20
	SRM_SRM_21          SRM = 21
	SRM_SRM_22          SRM = 22
	SRM_SRM_23          SRM = 23
	SRM_SRM_24          SRM = 24
	SRM_SRM_25          SRM = 25
	SRM_SRM_26          SRM = 26
	SRM_SRM_27          SRM = 27
	SRM_SRM_28          SRM = 28
	SRM_SRM_29          SRM = 29
	SRM_SRM_30          SRM = 30
)

// Enum value maps for SRM.
var (
	SRM_name = map[int32]string{
		0:  "SRM_UNSPECIFIED",
		1:  "SRM_1",
		2:  "SRM_2",
		3:  "SRM_3",
		4:  "SRM_4",
		5:  "SRM_5",
		6:  "SRM_6",
		7:  "SRM_7",
		8:  "SRM_8",
		9:  "SRM_9",
		10: "SRM_10",
		11: "SRM_11",
		12: "SRM_12",
		13: "SRM_13",
		14: "SRM_14",
		15: "SRM_15",
		16: "SRM_16",
		17: "SRM_17",
		18: "SRM_18",
		19: "SRM_19",
		20: "SRM_20",
		21: "SRM_21",
		22: "SRM_22",
		23: "SRM_23",
		24: "SRM_24",
		25: "SRM_25",
		26: "SRM_26",
		27: "SRM_27",
		28: "SRM_28",
		29: "SRM_29",
		30: "SRM_30",
	}
	SRM_value = map[string]int32{
		"SRM_UNSPECIFIED": 0,
		"SRM_1":           1,
		"SRM_2":           2,
		"SRM_3":           3,
		"SRM_4":           4,
		"SRM_5":           5,
		"SRM_6":           6,
		"SRM_7":           7,
		"SRM_8":           8,
		"SRM_9":           9,
		"SRM_10":          10,
		"SRM_11":          11,
		"SRM_12":          12,
		"SRM_13":          13,
		"SRM_14":          14,
		"SRM_15":          15,
		"SRM_16":          16,
		"SRM_17":          17,
		"SRM_18":          18,
		"SRM_19":          19,
		"SRM_20":          20,
		"SRM_21":          21,
		"SRM_22":          22,
		"SRM_23":          23,
		"SRM_24":          24,
		"SRM_25":          25,
		"SRM_26":          26,
		"SRM_27":          27,
		"SRM_28":          28,
		"SRM_29":          29,
		"SRM_30":          30,
	}
)

func (x SRM) Enum() *SRM {
	p := new(SRM)
	*p = x
	return p
}

func (x SRM) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SRM) Descriptor() protoreflect.EnumDescriptor {
	return file_beerproto_v1_srm_proto_enumTypes[0].Descriptor()
}

func (SRM) Type() protoreflect.EnumType {
	return &file_beerproto_v1_srm_proto_enumTypes[0]
}

func (x SRM) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SRM.Descriptor instead.
func (SRM) EnumDescriptor() ([]byte, []int) {
	return file_beerproto_v1_srm_proto_rawDescGZIP(), []int{0}
}

type Color struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             uint32                 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	R             uint32                 `protobuf:"varint,2,opt,name=r,proto3" json:"r,omitempty"`
	G             uint32                 `protobuf:"varint,3,opt,name=g,proto3" json:"g,omitempty"`
	B             uint32                 `protobuf:"varint,4,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Color) Reset() {
	*x = Color{}
	mi := &file_beerproto_v1_srm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_beerproto_v1_srm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_beerproto_v1_srm_proto_rawDescGZIP(), []int{0}
}

func (x *Color) GetA() uint32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Color) GetR() uint32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *Color) GetG() uint32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *Color) GetB() uint32 {
	if x != nil {
		return x.B
	}
	return 0
}

var file_beerproto_v1_srm_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*Color)(nil),
		Field:         123456783,
		Name:          "beerproto.v1.color",
		Tag:           "bytes,123456783,opt,name=color",
		Filename:      "beerproto/v1/srm.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional beerproto.v1.Color color = 123456783;
	E_Color = &file_beerproto_v1_srm_proto_extTypes[0]
)

var File_beerproto_v1_srm_proto protoreflect.FileDescriptor

const file_beerproto_v1_srm_proto_rawDesc = "" +
	"\n" +
	"\x16beerproto/v1/srm.proto\x12\fbeerproto.v1\x1a google/protobuf/descriptor.proto\"?\n" +
	"\x05Color\x12\f\n" +
	"\x01a\x18\x01 \x01(\rR\x01a\x12\f\n" +
	"\x01r\x18\x02 \x01(\rR\x01r\x12\f\n" +
	"\x01g\x18\x03 \x01(\rR\x01g\x12\f\n" +
	"\x01b\x18\x04 \x01(\rR\x01b*\xa4\a\n" +
	"\x03SRM\x12$\n" +
	"\x0fSRM_UNSPECIFIED\x10\x00\x1a\x0f\xfa\xd0\xf9\xd6\x03\t\x10\xff\x01\x18\xff\x01 \xff\x01\x12\x1d\n" +
	"\x05SRM_1\x10\x01\x1a\x12\xfa\xd0\xf9\xd6\x03\f\b\xff\x01\x10\xf3\x01\x18\xf9\x01 \x93\x01\x12\x1c\n" +
	"\x05SRM_2\x10\x02\x1a\x11\xfa\xd0\xf9\xd6\x03\v\b\xff\x01\x10\xf5\x01\x18\xf7\x01 \\\x12\x1c\n" +
	"\x05SRM_3\x10\x03\x1a\x11\xfa\xd0\xf9\xd6\x03\v\b\xff\x01\x10\xf6\x01\x18\xf5\x01 \x13\x12\x1c\n" +
	"\x05SRM_4\x10\x04\x1a\x11\xfa\xd0\xf9\xd6\x03\v\b\xff\x01\x10\xea\x01\x18\xe6\x01 \x15\x12\x1c\n" +
	"\x05SRM_5\x10\x05\x1a\x11\xfa\xd0\xf9\xd6\x03\v\b\xff\x01\x10\xe0\x01\x18\xd0\x01 \x1b\x12\x1c\n" +
	"\x05SRM_6\x10\x06\x1a\x11\xfa\xd0\xf9\xd6\x03\v\b\xff\x01\x10\xd5\x01\x18\xbc\x01 &\x12\x1c\n" +
	"\x05SRM_7\x10\a\x1a\x11\xfa\xd0\xf9\xd6\x03\v\b\xff\x01\x10\xcd\x01\x18\xaa\x01 7\x12\x1c\n" +
	"\x05SRM_8\x10\b\x1a\x11\xfa\xd0\xf9\xd6\x03\v\b\xff\x01\x10\xc1\x01\x18\x96\x01 <\x12\x1c\n" +
	"\x05SRM_9\x10\t\x1a\x11\xfa\xd0\xf9\xd6\x03\v\b\xff\x01\x10\xbe\x01\x18\x8c\x01 :\x12\x1d\n" +
	"\x06SRM_10\x10\n" +
	"\x1a\x11\xfa\xd0\xf9\xd6\x03\v\b\xff\x01\x10\xbe\x01\x18\x82\x01 :\x12\x1c\n" +
	"\x06SRM_11\x10\v\x1a\x10\xfa\xd0\xf9\xd6\x03\n" +
	"\b\xff\x01\x10\xc1\x01\x18z 7\x12\x1c\n" +
	"\x06SRM_12\x10\f\x1a\x10\xfa\xd0\xf9\xd6\x03\n" +
	"\b\xff\x01\x10\xbf\x01\x18q 8\x12\x1c\n" +
	"\x06SRM_13\x10\r\x1a\x10\xfa\xd0\xf9\xd6\x03\n" +
	"\b\xff\x01\x10\xbc\x01\x18g 3\x12\x1c\n" +
	"\x06SRM_14\x10\x0e\x1a\x10\xfa\xd0\xf9\xd6\x03\n" +
	"\b\xff\x01\x10\xb2\x01\x18` 3\x12\x1c\n" +
	"\x06SRM_15\x10\x0f\x1a\x10\xfa\xd0\xf9\xd6\x03\n" +
	"\b\xff\x01\x10\xa8\x01\x18X 9\x12\x1c\n" +
	"\x06SRM_16\x10\x10\x1a\x10\xfa\xd0\xf9\xd6\x03\n" +
	"\b\xff\x01\x10\x98\x01\x18S 6\x12\x1c\n" +
	"\x06SRM_17\x10\x11\x1a\x10\xfa\xd0\xf9\xd6\x03\n" +
	"\b\xff\x01\x10\x8d\x01\x18L 2\x12\x1b\n" +
	"\x06SRM_18\x10\x12\x1a\x0f\xfa\xd0\xf9\xd6\x03\t\b\xff\x01\x10|\x18E -\x12\x1b\n" +
	"\x06SRM_19\x10\x13\x1a\x0f\xfa\xd0\xf9\xd6\x03\t\b\xff\x01\x10k\x18: \x1e\x12\x1b\n" +
	"\x06SRM_20\x10\x14\x1a\x0f\xfa\xd0\xf9\xd6\x03\t\b\xff\x01\x10]\x184 \x1a\x12\x1b\n" +
	"\x06SRM_21\x10\x15\x1a\x0f\xfa\xd0\xf9\xd6\x03\t\b\xff\x01\x10N\x18* \f\x12\x1b\n" +
	"\x06SRM_22\x10\x16\x1a\x0f\xfa\xd0\xf9\xd6\x03\t\b\xff\x01\x10J\x18' '\x12\x1b\n" +
	"\x06SRM_23\x10\x17\x1a\x0f\xfa\xd0\xf9\xd6\x03\t\b\xff\x01\x106\x18\x1f \x1b\x12\x1b\n" +
	"\x06SRM_24\x10\x18\x1a\x0f\xfa\xd0\xf9\xd6\x03\t\b\xff\x01\x10&\x18\x17 \x16\x12\x1b\n" +
	"\x06SRM_25\x10\x19\x1a\x0f\xfa\xd0\xf9\xd6\x03\t\b\xff\x01\x10#\x18\x17 \x16\x12\x1b\n" +
	"\x06SRM_26\x10\x1a\x1a\x0f\xfa\xd0\xf9\xd6\x03\t\b\xff\x01\x10\x19\x18\x10 \x0f\x12\x1b\n" +
	"\x06SRM_27\x10\x1b\x1a\x0f\xfa\xd0\xf9\xd6\x03\t\b\xff\x01\x10\x16\x18\x10 \x0f\x12\x1b\n" +
	"\x06SRM_28\x10\x1c\x1a\x0f\xfa\xd0\xf9\xd6\x03\t\b\xff\x01\x10\x12\x18\r \f\x12\x1b\n" +
	"\x06SRM_29\x10\x1d\x1a\x0f\xfa\xd0\xf9\xd6\x03\t\b\xff\x01\x10\x10\x18\v \n" +
	"\x12\x1b\n" +
	"\x06SRM_30\x10\x1e\x1a\x0f\xfa\xd0\xf9\xd6\x03\t\b\xff\x01\x10\x05\x18\v \n" +
	":R\n" +
	"\x05color\x12!.google.protobuf.EnumValueOptions\x18\x8f\x9a\xef: \x01(\v2\x13.beerproto.v1.ColorR\x05color\x88\x01\x01B\xa9\x01\n" +
	"\x10com.beerproto.v1B\bSrmProtoP\x01Z:github.com/beerproto/beerproto_go/beerproto/v1;beerprotov1\xa2\x02\x03BXX\xaa\x02\fBeerproto.V1\xca\x02\fBeerproto\\V1\xe2\x02\x18Beerproto\\V1\\GPBMetadata\xea\x02\rBeerproto::V1b\x06proto3"

var (
	file_beerproto_v1_srm_proto_rawDescOnce sync.Once
	file_beerproto_v1_srm_proto_rawDescData []byte
)

func file_beerproto_v1_srm_proto_rawDescGZIP() []byte {
	file_beerproto_v1_srm_proto_rawDescOnce.Do(func() {
		file_beerproto_v1_srm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beerproto_v1_srm_proto_rawDesc), len(file_beerproto_v1_srm_proto_rawDesc)))
	})
	return file_beerproto_v1_srm_proto_rawDescData
}

var file_beerproto_v1_srm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_beerproto_v1_srm_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_beerproto_v1_srm_proto_goTypes = []any{
	(SRM)(0),                              // 0: beerproto.v1.SRM
	(*Color)(nil),                         // 1: beerproto.v1.Color
	(*descriptorpb.EnumValueOptions)(nil), // 2: google.protobuf.EnumValueOptions
}
var file_beerproto_v1_srm_proto_depIdxs = []int32{
	2, // 0: beerproto.v1.color:extendee -> google.protobuf.EnumValueOptions
	1, // 1: beerproto.v1.color:type_name -> beerproto.v1.Color
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_beerproto_v1_srm_proto_init() }
func file_beerproto_v1_srm_proto_init() {
	if File_beerproto_v1_srm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beerproto_v1_srm_proto_rawDesc), len(file_beerproto_v1_srm_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_beerproto_v1_srm_proto_goTypes,
		DependencyIndexes: file_beerproto_v1_srm_proto_depIdxs,
		EnumInfos:         file_beerproto_v1_srm_proto_enumTypes,
		MessageInfos:      file_beerproto_v1_srm_proto_msgTypes,
		ExtensionInfos:    file_beerproto_v1_srm_proto_extTypes,
	}.Build()
	File_beerproto_v1_srm_proto = out.File
	file_beerproto_v1_srm_proto_goTypes = nil
	file_beerproto_v1_srm_proto_depIdxs = nil
}
