name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  Proto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout beerproto
        uses: actions/checkout@v2
        with:
          repository: beerproto/beerproto
          path: proto
      - name: Buf generate
        uses: bufbuild/buf-setup-action@v1
        working-directory: ./proto
        run: buf generate beerprotoapis --template=buf.gen.go.yaml
      - name: Git Commit on Workflow
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Updating beer.pb.go
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.${{ github.run_number }}.0
          body: CI Release ${{ github.ref }}
          draft: false
          prerelease: false
