name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  Proto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout beerproto
        uses: actions/checkout@v2
        with:
          repository: beerproto/beerproto
          path: proto
      - uses: actions/setup-go@v2.0.3
      - run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - run: echo $(go env GOPATH)/bin >> $GITHUB_PATH
      - uses: bufbuild/buf-setup-action@v1
      - name: Buf generate
        run: buf generate beerprotoapis --template=buf.gen.go.yaml
        working-directory: ./proto
      - run: rm -R ./v1
      - name: Move beer file
        run: mv ./proto/gen/proto/go/github.com/beerproto/beerproto_go/beerproto/v1 ./
      - run: rm -R ./proto
      - name: Push
        uses: actions-x/commit@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "master"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.${{ github.run_number }}.0
          body: CI Release ${{ github.ref }}
          draft: false
          prerelease: false
