name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Proto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout beerproto
        uses: actions/checkout@v2
        with:
          repository: beerproto/beerproto
          path: proto
      - uses: actions/setup-go@v2.0.3
      - run: echo $(go env GOPATH)/bin >> $GITHUB_PATH
      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - name: Buf generate
        run: buf generate beerprotoapis --template=buf.gen.go.yaml
        working-directory: ./proto
      - name: Move beer file
        run: mv ./proto/gen/beerproto/v1/* ./
      - run: rm -R ./proto
      - name: Push
        uses: actions-x/commit@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "master"
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Tag the commit the Push step just created, not the one we checked out.
          git fetch origin master
          gh release create "v1.${{ github.run_number }}.0" \
            --target "$(git rev-parse origin/master)" \
            --title "v1.${{ github.run_number }}.0" \
            --notes "CI Release ${{ github.ref }}"
