name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  Proto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout beerproto
        uses: actions/checkout@v2
        with:
          repository: beerproto/beerproto
          path: proto
      - uses: bufbuild/buf-setup-action@v1
      - run: buf --version
      - run: buf generate beerprotoapis --template=buf.gen.go.yaml
      - name: Git Commit on Workflow
        uses: matheusalbino/git-commit@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: Updating beer.pb.go
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.${{ github.run_number }}.0
          body: CI Release ${{ github.ref }}
          draft: false
          prerelease: false
